### ISSUE TITLE
Tibian Prize Exhibition Expansion

### ISSUE THREAD

**Issue by Hunter-of-Dragoes** [tibiamaps/tibia-map-data#101]
With the recent fansite item implementations, the Tibian Prize Exhibition was expanded.
![Minimap_WaypointCost_32256_32000_10](https://user-images.githubusercontent.com/23020634/95489166-e2bbab80-096c-11eb-8ea0-828942ba9fc9.png)
![Minimap_Color_32256_32000_10](https://user-images.githubusercontent.com/23020634/95489053-b142e000-096c-11eb-95ba-f8ce6e677389.png)

**Comment by mathiasbynens** [comment]
Thanks! Working on merging this now. 

Tip for the next time: unfortunately, GitHub renames images when you upload them inline like this, and also potentially compresses them. It's much easier if you could ZIP the images and then upload the ZIP instead, as that way we're certain the 100% original image data is preserved (and I don't have to go looking for the original file names in the code). Thanks :)
