### ISSUE TITLE
Some minimap files not being recognized

### ISSUE THREAD

**Issue by mathiasbynens** [tibiamaps/tibia-map-data#105]
@LeeKunTibia reported an issue with a few minimap files not being recognized by the client.

Here's a ZIP file with the “good” (explored in the Tibia client, and thus accepted by the client) and “bad” (generated by our scripts, and somehow not accepted by the client) files.

[`issue.zip`](https://github.com/tibiamaps/tibia-map-data/files/5423580/issue.zip)

**Comment by mathiasbynens** [comment]
The visual map data is different (pixels are not 100% the same):

![](https://user-images.githubusercontent.com/81942/96889310-c3ea0880-1486-11eb-8599-24b8d91b4673.png)

...so it's hard to compare the PNG data with `vbindiff`. I'll import the good files into our map data, and then compare against our generated versions so that it's a 1:1 comparison.

**Comment by LeeKunTibia** [comment]
Here are the corresponding path files of this 2 floors:

[Path.zip](https://github.com/tibiamaps/tibia-map-data/files/5423633/Path.zip)

**Comment by mathiasbynens** [comment]
Since merging Lee’s files into our data, our generated files are now 100% identical byte-for-byte to the client-generated files.

**Comment by mathiasbynens** [comment]
So we've established that there's nothing inherently wrong with the files we generate. I wonder what else is going on though. Perhaps the Tibia client was changed to now require a corresponding `WaypointCost` file before it accepts a `Color` file?

**Comment by mathiasbynens** [comment]
> Perhaps the Tibia client was changed to now require a corresponding `WaypointCost` file before it accepts a `Color` file?

Lee confirmed that was what prevented him from seeing the surrounding floors (for which only `Color` data was available). We should update our scripts to generate "empty" `WaypointCost` files where needed.

**Comment by LeeKunTibia** [comment]
I got the explored waypoint files from a friend, together with the Cyclopedia-generated map files the problems with this location should be solved.

[Furious Crater with Waypoints.zip](https://github.com/tibiamaps/tibia-map-data/files/5427228/Furious.Crater.with.Waypoints.zip)

**Comment by mathiasbynens** [comment]
We now force the creation of missing `WaypointCost` files. With our current map data, there's only one such instance, for [this area](https://tibiamaps.io/map#33402,32644,0:2):

```
Creating missing `WaypointCost` file: 33280_32512_0
```
