### ISSUE TITLE
Winter Update 2020

### ISSUE THREAD

**Issue by LeeKunTibia** [tibiamaps/tibia-map-data#108]
The Winter Update 2020 is near! This time it appears that there aren't many new areas. So far most of it seems to be concentrated north of Kilmaresh on the ground floor and two floors below, with some other small pieces on the floors above ground.

This is a first batch that covers most of it, but not everything. 

**Important**: Some of these files overlap with the Orcsoberfest/Winterlight Solstice area, so this must be taken into account when using them.

Later on I will use the Cyclopedia map to generate detailed files for the ground floors and above, with all mountain parts etc.

[Wu 2020.zip](https://github.com/tibiamaps/tibia-map-data/files/5483738/Wu.2020.zip)

**Comment by mathiasbynens** [comment]
For future reference, these are the files that overlap with the special Orcsoberfest/Percht Island maps:

```
$ for i in *.png; do if [ -f ~/projects/tibia-map-data/extra/orcsoberfest-island/$i ]; then echo $i; fi; done
Minimap_Color_33792_30976_7.png
Minimap_WaypointCost_33792_30976_7.png
```

**Comment by LeeKunTibia** [comment]
Here's a new batch. It has the same files as before, but with more explored areas. Also, the ground floors and above have been extracted from the Cyclopedia. 

It also includes some task rooms which are on the last floor, [here](https://tibiamaps.io/map#33939,31363,15:0). This rooms aren't fully explored so more work will need to be done on them. 

I'm also updating the markers right now. 

[Second Batch.zip](https://github.com/tibiamaps/tibia-map-data/files/5495102/Second.Batch.zip)

**Comment by LeeKunTibia** [comment]
Third batch of the same areas. Hunter is going to need the most updated version of all files to explore the "new" houses so I'm sending these to avoid losing any progress. 

It's the same areas with better Path finding and floors from the Cyclopedia that were missing on the last batch. 

[Third Batch.zip](https://github.com/tibiamaps/tibia-map-data/files/5520138/Third.Batch.zip)

I think we can start listing pending maps:

- [ ] Complete area of the fight against the final boss. (33792_31232_15)
- [ ] Existing areas where Pirat raids occur and there were small changes on the amount of objects (tree, rocks, etc). Known raids are on Thais, Liberty Bay, Port Hope, Darashia and Krailos.

**Comment by mathiasbynens** [comment]
@LeeKunTibia Thanks! Done in a09e663a84338dac592cd9ca7b8f2ad975e611b0 + 5db3c04e776bf0eea4dc8e2afb4820983f41ccc9. @Hunter-of-Dragoes, the downloads should be up to date in an hour or so.

**Comment by Hunter-of-Dragoes** [comment]
I explored a little better the cave between Issavi and Rascacoon + the Stealth Mission area (including upper floor, explored with levitate).
[Map.zip](https://github.com/tibiamaps/tibia-map-data/files/5541618/Map.zip)

**Comment by mathiasbynens** [comment]
@Hunter-of-Dragoes Thanks! Maps added in https://github.com/tibiamaps/tibia-map-data/commit/7b18b6b1fdb479ddd55fdfd6b8adbea8c6947e10 and markers added in https://github.com/tibiamaps/tibia-map-data/commit/2fc57c1addf0d316fee5a198a46791752fb5ae6b.

**Comment by Hunter-of-Dragoes** [comment]
> It also includes some task rooms which are on the last floor, [here](https://tibiamaps.io/map#33939,31363,15:0). This rooms aren't fully explored so more work will need to be done on them.

I was able to explore the Supply Mission rooms - the rooms t0 the northeast - a little more.
[Supply Mission Map.zip](https://github.com/tibiamaps/tibia-map-data/files/5560399/Supply.Mission.Map.zip)

**Comment by mathiasbynens** [comment]
@Hunter-of-Dragoes Merged!

**Comment by LeeKunTibia** [comment]
Ratmiral Blackwhiskers boss area ([here](https://tibiamaps.io/map#33907,31349,15:1)):

[Ratmiral.zip](https://github.com/tibiamaps/tibia-map-data/files/5648322/Ratmiral.zip)

**Comment by LeeKunTibia** [comment]
> 
> 
> For future reference, these are the files that overlap with the special Orcsoberfest/Percht Island maps:
> 
> ```
> $ for i in *.png; do if [ -f ~/projects/tibia-map-data/extra/orcsoberfest-island/$i ]; then echo $i; fi; done
> Minimap_Color_33792_30976_7.png
> Minimap_WaypointCost_33792_30976_7.png
> ```

Just a note that you may want to update this reference with the other floors ;P

**Comment by mathiasbynens** [comment]
> > For future reference, these are the files that overlap with the special Orcsoberfest/Percht Island maps:
> > ```
> > $ for i in *.png; do if [ -f ~/projects/tibia-map-data/extra/orcsoberfest-island/$i ]; then echo $i; fi; done
> > Minimap_Color_33792_30976_7.png
> > Minimap_WaypointCost_33792_30976_7.png
> > ```
> 
> Just a note that you may want to update this reference with the other floors ;P

Indeed! The comment refers to the ZIP that was provided at that point. The same command must be re-run with any other Winter Update-related maps.

**Comment by LeeKunTibia** [comment]
There were some rooms missing from The Mirrored Nightmare's +1 floor which I explored today:

[Minimap_Color_33792_30976_10.zip](https://github.com/tibiamaps/tibia-map-data/files/5923143/Minimap_Color_33792_30976_10.zip)

**Comment by LeeKunTibia** [comment]
I think we can close this, there's no known pendency.
