### ISSUE TITLE
Walkable sqm as yellow on path file

### ISSUE THREAD

**Issue by alfredomtx** [tibiamaps/tibia-map-data#110]
Hello,

Just wanna report that the SQM in the coordinate `https://tibiamaps.io/map#32931,32078,8:3`, is a yellow SQM on the path.png file `floor-08-path.png`. I think it shouldn't be since it is a normal walkable SQM(wooden floor)

![wrong_sqm_path](https://user-images.githubusercontent.com/20379136/100040907-ef924280-2de6-11eb-9389-bcf6fa5a0f1f.png)
.
 
I don't know if there is some way, or what would be the right way that I could fix it, may be just painting this pixel as gray(like the others around) on paint? And then make a pull request here to help you guys solving this and contribute with the project.

Anyways, best regards!

**Comment by mathiasbynens** [comment]
Thanks for the report, @alfredomtx! 

> I don't know if there is some way, or what would be the right way that I could fix it, may be just painting this pixel as gray(like the others around) on paint? And then make a pull request here to help you guys solving this and contribute with the project.

The best way to do it would be to:

1. install our latest map data
2. then open Tibia client
3. explore that area in-game
4. and then send us a ZIP with the `Minimap_WaypointCost_32768_32000_8.png` file.

(Step 1 is important because it makes sure there are no other, possibly undesired changes to the file.) Do you want to give that a try?

**Comment by alfredomtx** [comment]
Hello, 

Here are the WaypointCost file of this area and also the WaypointColor, since I found more wrong pixels in the `floor-08-map.png` file.

![image](https://user-images.githubusercontent.com/20379136/100152921-2ec1a180-2e82-11eb-8c47-4e7fcdbb8495.png)

[Uploading Minimap_
[Minimap_Color_32768_32000_8.zip](https://github.com/tibiamaps/tibia-map-data/files/5592827/Minimap_Color_32768_32000_8.zip)
WaypointCost_32768_32000_8.zip…]()

**Comment by alfredomtx** [comment]
I have another question, is there a public repository of the `Minimap_Color/WaypointCost_XXXXX_YYYYY_Z.png` files you use to generate the tibiamaps installer(and also the tibia map png files)?

I would like to be able to download those files one by one from your repository, from a direct link, like we are able with the full map files (ex: https://tibiamaps.github.io/tibia-map-data/floor-07-map.png).

I've made a script that generates the same `floor-XX-map/cost.png` files putting together all the files from Tibia's minimap folder,
I'm thinking of some way to make it easier to help you fix the wrong `floor-XX-map/cost.png` by sending in a more automatic way the `Minimap_Color/WaypointCost_XXXXX_YYYYY_Z.png` files, or another way maybe.

Thanks for your attention!
Your project is really so useful for all Tibia's community.

**Comment by mathiasbynens** [comment]
> I've made a script that generates the same floor-XX-map/cost.png files putting together all the files from Tibia's minimap folder,

Have you tried using our scripts for this? It just works.

> I would like to be able to download those files one by one from your repository, from a direct link, like we are able with the full map files 

You can either follow the instructions in the README to convert the `data/*.png` files to the `minimap/*.png` format, or look at the snapshots here: https://github.com/tibiamaps/tibia-map-data/tree/gh-pages/minimap-with-markers
