### ISSUE TITLE
Cannot make minimap/* -> data/*

### ISSUE THREAD

**Issue by ErikasKontenis** [tibiamaps/tibia-map-data#111]
Hello,

I have downloaded the LTS of the NodeJs:
$ node --version
v14.15.1
And installed the npm packages as written in the setup instructions however once I run "tibia-maps --from-minimap=./minimap --output-dir=./data"
It successfully runs without any errors and creates a data folder however it contains only single file of: bounds.json which has in its content only this nulls everywhere
{
	"xMin": null,
	"xMax": null,
	"yMin": null,
	"yMax": null,
	"zMin": null,
	"zMax": null,
	"width": null,
	"height": null,
	"floorIDs": []
}

Maybe I am missing something and such experience is a pretty much known issue for newcomer to experience? Thank you I am looking forward your reply!

**Comment by mathiasbynens** [comment]
What does `ls ./minimap` tell you?

**Comment by mathiasbynens** [comment]
I'll close this issue since it's not an issue with the map data, but feel free to continue replying here and I'll try to help you out!
