### ISSUE TITLE
Kazzordoon bless fire fields - non walkable path

### ISSUE THREAD

**Issue by alfredomtx** [tibiamaps/tibia-map-data#112]
Hello, i've noticed that the bridge to the bless NPC of Kazordoon has wrong path tiles in the "floor-11-path.png" file.

Here is the  the fixed waypoint cost file from my tibia minimap files.
[Minimap_WaypointCost_32512_31744_11.zip](https://github.com/tibiamaps/tibia-map-data/files/5681686/Minimap_WaypointCost_32512_31744_11.zip)

![image](https://user-images.githubusercontent.com/20379136/101956773-ec68c600-3bde-11eb-9336-d2bad2e2d4e2.png)

**Comment by mathiasbynens** [comment]
> `Minimap_WaypointCost_32512_31744_11.zip`

The `*.png` is not a file that was generated by the Tibia client (I can tell by the palette). Are you sure you didn't manually edit this?

The current pathfinding data seems correct for the server state after server save. There are fire fields on the yellow/unwalkable tiles. What exactly is wrong in the current data?

**Comment by alfredomtx** [comment]
Hello, I guarantee you I didn't manually edit the .png file, I closed Tibia client and got the .png from its minimap folder, if you want I can do it again and send it.

So it is correct for it to show the fire field SQMs as non-walkable after server save? (I didn't check after server save)

If you go there with your character and close Tibia client, you will see that the .png file generated doesn't have those yellow SQMs on the fire field ones, all are the same gray tone of walkable SQMs - even on the ones that have fire fields.

**Comment by LeeKunTibia** [comment]
It's that old issue that also caused creatures and fields created by players to be saved on the path file. This doesn't happen anymore even with the fields there, so the TibiaMaps file is indeed outdated. In this specific case though it won't make a big difference since the fields are almost always there anyway, so mapclicking still won't work. 

Nevertheless I guess it doesn't hurt to update this area, as we've been doing with [other areas](https://github.com/tibiamaps/tibia-map-data/issues/102).

**Comment by alfredomtx** [comment]
> It's that old issue that also caused creatures and fields created by players to be saved on the path file. This doesn't happen anymore even with the fields there, so the TibiaMaps file is indeed outdated. In this specific case though it won't make a big difference since the fields are almost always there anyway, so mapclicking still won't work.
> 
> Nevertheless I guess it doesn't hurt to update this area, as we've been doing with [other areas](https://github.com/tibiamaps/tibia-map-data/issues/102).

Do you want to close this issue and I send the new Cost file in the https://github.com/tibiamaps/tibia-map-data/issues/102 topic?
