### ISSUE TITLE
Difference between cylopedia

### ISSUE THREAD

**Issue by emceef94** [tibiamaps/tibia-map-data#113]
Hello,
I have found a small difference of 4 pixels between the maps and cyclopedia map

In minimap_color_32768_32000_7 pixels [(141, 83), (142, 83), (143, 83), (144, 83)] are different

**Comment by LeeKunTibia** [comment]
The area are [these fields](https://tibiamaps.io/map#32910,32083,7:2) on Venore's main depot. 

Here's the updated file: 
[Minimap_Color_32768_32000_7.zip](https://github.com/tibiamaps/tibia-map-data/files/5802363/Minimap_Color_32768_32000_7.zip)

**Comment by mathiasbynens** [comment]
Thanks!
