### ISSUE TITLE
Minotaur Cult Cave - Mountain pixels differences

### ISSUE THREAD

**Issue by alfredomtx** [tibiamaps/tibia-map-data#114]
Hello,

The Gray "Mountain" pixels of the Mino Cult are not completely shown on Tibiamaps' map, as you can see below.
If you walk in the corners of the Cave you'll see that the missing gray pixels will be opened.

Do you want me to send the "minimap_colors_xxx" .png files of the respective areas of this cave?

Tibiamaps' map:
![image](https://user-images.githubusercontent.com/20379136/103937600-bba97d00-5107-11eb-9185-90bb627b80a9.png)

Cyclopedia map:
![image](https://user-images.githubusercontent.com/20379136/103937450-8866ee00-5107-11eb-95f1-15396c0b86f4.png)

**Comment by alfredomtx** [comment]
The same happens in the Venore Salamanders Cave(south and west caves)

**Comment by mathiasbynens** [comment]
@LeeKunTibia Could you post the full Cyclopedia images? I could then do the cropping.

**Comment by mathiasbynens** [comment]
Or yes, @alfredomtx, it would be nice if you could send the `minimap` files directly -- that's even easier.

**Comment by LeeKunTibia** [comment]
> 
> 
> @LeeKunTibia Could you post the full Cyclopedia images? I could then do the cropping.

It wouldn't help in this case, that's underground. His Cyclopedia map is more complete because he explored it. In any case, if necessary I can go there and get all the missing corners as well.

**Comment by alfredomtx** [comment]
Yep, the Cyclopedia map in my case is opened because I explored this area ingame.

Here we go:
- Mino Cult Cave:
![Minimap_Color_31744_32256_8](https://user-images.githubusercontent.com/20379136/104255780-96df3d80-5458-11eb-8d51-6eafaaa7a5e0.png)

- Salamanders Venore:
![Minimap_Color_32768_32000_10](https://user-images.githubusercontent.com/20379136/104255790-9c3c8800-5458-11eb-9629-be979107bd8f.png)

**Comment by alfredomtx** [comment]
> Or yes, @alfredomtx, it would be nice if you could send the `minimap` files directly -- that's even easier.

Sorry, when you mean "send the `minimap` files directly", do you mean sending the .png file? Or do you prefer a zipped file with the png in it?

**Comment by mathiasbynens** [comment]
@alfredomtx Sorry for being unclear. A ZIP file containing the PNGs is best, because we need the original client-generated PNGs. Thanks!

**Comment by alfredomtx** [comment]
> @alfredomtx Sorry for being unclear. A ZIP file containing the PNGs is best, because we need the original client-generated PNGs. Thanks!

Got it!

**Comment by mathiasbynens** [comment]
I guess you closed this by accident? :) Could you please upload the PNGs in a ZIP?

**Comment by alfredomtx** [comment]
> I guess you closed this by accident? :) Could you please upload the PNGs in a ZIP?

Hello, sorry for the late response, sure it was closed by mistake, my bad.

Here are the .zip files for the mino cult cave, floor 8 and 9:
[mino_cult.zip](https://github.com/tibiamaps/tibia-map-data/files/5844350/mino_cult.zip)

Salamander Cave:
[Minimap_Color_32768_32000_10.zip](https://github.com/tibiamaps/tibia-map-data/files/5844360/Minimap_Color_32768_32000_10.zip)

**Comment by mathiasbynens** [comment]
Merged. Thanks!
