### ISSUE TITLE
Differences found in some areas

### ISSUE THREAD

**Issue by alfredomtx** [tibiamaps/tibia-map-data#115]
Hello, 

I found more differences in some other places in Tibia:

- Pirats Island (gray mountain pixel near the hole) [(here)](https://tibiamaps.io/map#33790,31340,7:2):
[Minimap_Color_33536_31232_7.zip](https://github.com/tibiamaps/tibia-map-data/files/5844392/Minimap_Color_33536_31232_7.zip)

- [Feyrist weakened -1 and -2](https://tibiamaps.io/map#33547,32268,8:1) (gray mountain pixels):
[feyrist.zip](https://github.com/tibiamaps/tibia-map-data/files/5844395/feyrist.zip)

- [Swamp Troll Venore -1](https://tibiamaps.io/map#32938,32222,8:2) (brown pixels at entrance):
[Minimap_Color_32768_32000_8.zip](https://github.com/tibiamaps/tibia-map-data/files/5844405/Minimap_Color_32768_32000_8.zip)

**Comment by mathiasbynens** [comment]
Thanks, Alfredo! I've merged the changes 👍
