### ISSUE TITLE
Minimap differences - Pirats Cave

### ISSUE THREAD

**Issue by alfredomtx** [tibiamaps/tibia-map-data#116]
Hello,

There are some differences of some "gray mountain" pixels not discovered in some corners of the cave, such as [here](https://tibiamaps.io/map#33799,31348,8:2).

Here is the new minimap file:
[Minimap_Color_33792_31232_8.zip](https://github.com/tibiamaps/tibia-map-data/files/5858596/Minimap_Color_33792_31232_8.zip)

**Comment by mathiasbynens** [comment]
Thanks — done!
