### ISSUE TITLE
Pìxel differences Stonerefiner's Cave

### ISSUE THREAD

**Issue by alfredomtx** [tibiamaps/tibia-map-data#117]
Hello,

Found 2 differences in the map at Stonerefiner's Cave, [here](https://tibiamaps.io/map#33051,31979,13:2) and [here](https://tibiamaps.io/map#33074,31984,13:2).

I will stop soon to learn how to use the git command line tools to submit pull requests instead of opening issues to facilitate the work for you okay ;)

Here is the new minimap file:
[Minimap_Color_33024_31744_13.zip](https://github.com/tibiamaps/tibia-map-data/files/5868922/Minimap_Color_33024_31744_13.zip)

**Comment by mathiasbynens** [comment]
Thanks!

> I will stop soon to learn how to use the git command line tools to submit pull requests instead of opening issues to facilitate the work for you okay ;)

Don't worry, what you're currently doing (sending the minimap PNGs) is probably the fastest and easiest to review workflow for me!

**Comment by alfredomtx** [comment]
> Thanks!
> 
> > I will stop soon to learn how to use the git command line tools to submit pull requests instead of opening issues to facilitate the work for you okay ;)
> 
> Don't worry, what you're currently doing (sending the minimap PNGs) is probably the fastest and easiest to review workflow for me!

Oh okay, that's good to know, I'm gonna continue this way then.
