### ISSUE TITLE
Dawnport Minotaur Cave is outdated(must explore again)

### ISSUE THREAD

**Issue by alfredomtx** [tibiamaps/tibia-map-data#118]
Hello,

I've noticed that the Minotaur Cave of Dawnport have parts outdated.
I didn't explore the cave to update the minimap pixels(and to be sure there are more parts outdated), the differences I noticed was going down from the 2 Troll Mountain ladders, [here](https://tibiamaps.io/map#32055,31898,9:2) and [here](https://tibiamaps.io/map#32074,31897,9:2).

I'm not willing to explore the mino cave in Dawnport, I don't like there very much :/
Maybe we can keep this issue open, in case someone else wants to explore there, or perhaps I go there another day and try to explore it myself, I opened this issue to keep track of this.

There are many pixels that are different, some gray of the ground and some red ones in the lava, 2 examples: [here](https://tibiamaps.io/map#32069,31891,9:2) and [here](https://tibiamaps.io/map#32075,31902,9:2).

Anyway, here is the minimap file to see the differences just from the point of view of the 2 ladders:
[Minimap_Color_32000_31744_9.zip](https://github.com/tibiamaps/tibia-map-data/files/5870650/Minimap_Color_32000_31744_9.zip)

**Comment by mathiasbynens** [comment]
Thanks! I've applied your changed and indeed, let's keep the issue open in case someone wants to go and re-explore the cave. 👍

**Comment by muriloricci** [comment]
I spent some minutes now and got the maps updated. :)
[minimap dawnport.zip](https://github.com/tibiamaps/tibia-map-data/files/8033259/minimap.dawnport.zip)

**Comment by mathiasbynens** [comment]
I guess this one can be closed now.
