### ISSUE TITLE
Ankrahmun Arito's task map differences

### ISSUE THREAD

**Issue by alfredomtx** [tibiamaps/tibia-map-data#120]
Hello,

There are some undiscovered pixels in the underground [here](https://tibiamaps.io/map#33179,32861,9:3)

Here is the new minimap file:
[Minimap_Color_33024_32768_9.zip](https://github.com/tibiamaps/tibia-map-data/files/5897031/Minimap_Color_33024_32768_9.zip)

**Comment by mathiasbynens** [comment]
Thanks!
