### ISSUE TITLE
Amazon Camp -1

### ISSUE THREAD

**Issue by alfredomtx** [tibiamaps/tibia-map-data#121]
Hello

Opened a few more Gray mountain pixels, such as [here](https://tibiamaps.io/map#32900,31864,8:2).

Minimap file:
[Minimap_Color_32768_31744_8.zip](https://github.com/tibiamaps/tibia-map-data/files/5915474/Minimap_Color_32768_31744_8.zip)

**Comment by mathiasbynens** [comment]
Thanks!
