### ISSUE TITLE
Pirats & Exotic Spider cave

### ISSUE THREAD

**Issue by alfredomtx** [tibiamaps/tibia-map-data#122]
Hello,

Found a few more differences in the caves, [here](https://tibiamaps.io/map#33919,31394,8:2) and [here](https://tibiamaps.io/map#33881,31370,9:2).

Minimap files:
[Minimap_Color_33792_31232_9.zip](https://github.com/tibiamaps/tibia-map-data/files/5915803/Minimap_Color_33792_31232_9.zip)
[Minimap_Color_33792_31232_8.zip](https://github.com/tibiamaps/tibia-map-data/files/5915804/Minimap_Color_33792_31232_8.zip)

**Comment by mathiasbynens** [comment]
Thanks! Btw, next time feel free to put all PNGs in the same ZIP if that's easier for you. There's no need to create a separate ZIP for each one. 👍

**Comment by alfredomtx** [comment]
> Thanks! Btw, next time feel free to put all PNGs in the same ZIP if that's easier for you. There's no need to create a separate ZIP for each one. 👍

Will do, thanks!
