### ISSUE TITLE
Professor Maxxen Oramond

### ISSUE THREAD

**Issue by alfredomtx** [tibiamaps/tibia-map-data#123]
Hello,

Found 1 different pixel at this cave, [here](https://tibiamaps.io/map#33614,32073,15:2).

Minimap file:
[Minimap_Color_33536_32000_15.zip](https://github.com/tibiamaps/tibia-map-data/files/5927652/Minimap_Color_33536_32000_15.zip)

**Comment by mathiasbynens** [comment]
Thanks!
