### ISSUE TITLE
Stonerefiners Venore

### ISSUE THREAD

**Issue by alfredomtx** [tibiamaps/tibia-map-data#124]
Hello,

Found a few more gray pixels, [here](https://tibiamaps.io/map#33086,31994,13:2).

Minimap file:
[Minimap_Color_33024_31744_13.zip](https://github.com/tibiamaps/tibia-map-data/files/5928486/Minimap_Color_33024_31744_13.zip)

**Comment by alfredomtx** [comment]
Complementing, there is a wrong black pix [here](https://tibiamaps.io/map#33066,32031,13:3).

Minimap file:
[Minimap_Color_33024_32000_13.zip](https://github.com/tibiamaps/tibia-map-data/files/5933520/Minimap_Color_33024_32000_13.zip)

**Comment by mathiasbynens** [comment]
Thanks!
