### ISSUE TITLE
Gray Island 

### ISSUE THREAD

**Issue by alfredomtx** [tibiamaps/tibia-map-data#126]
Hello,

There are some differences [here](https://tibiamaps.io/map#33468,31311,7:2).

Minimap file:
[Minimap_Color_33280_31232_7.zip](https://github.com/tibiamaps/tibia-map-data/files/5937825/Minimap_Color_33280_31232_7.zip)
[Minimap_WaypointCost_33280_31232_7.zip](https://github.com/tibiamaps/tibia-map-data/files/5939712/Minimap_WaypointCost_33280_31232_7.zip)

**Comment by mathiasbynens** [comment]
Thanks!
