### ISSUE TITLE
Minimap cost files from last issues

### ISSUE THREAD

**Issue by alfredomtx** [tibiamaps/tibia-map-data#127]
Hello,

I've opened many issues in the past weeks with updated minimap files, but today I realized, I didn't sent the Cost file of those places.

I'm gonna use this issue to send those files okay?

- [x] https://github.com/tibiamaps/tibia-map-data/issues/125
- [x] https://github.com/tibiamaps/tibia-map-data/issues/124 
- [x] https://github.com/tibiamaps/tibia-map-data/issues/123
- [ ] https://github.com/tibiamaps/tibia-map-data/issues/122
- [x] https://github.com/tibiamaps/tibia-map-data/issues/119

**Comment by alfredomtx** [comment]
https://github.com/tibiamaps/tibia-map-data/issues/125
[Minimap_WaypointCost_32256_31488_5.zip](https://github.com/tibiamaps/tibia-map-data/files/5939716/Minimap_WaypointCost_32256_31488_5.zip)

**Comment by alfredomtx** [comment]
https://github.com/tibiamaps/tibia-map-data/issues/124
[124.zip](https://github.com/tibiamaps/tibia-map-data/files/5939721/124.zip)

**Comment by alfredomtx** [comment]
https://github.com/tibiamaps/tibia-map-data/issues/119
[Minimap_WaypointCost_33280_32000_8.zip](https://github.com/tibiamaps/tibia-map-data/files/5939727/Minimap_WaypointCost_33280_32000_8.zip)

**Comment by alfredomtx** [comment]
https://github.com/tibiamaps/tibia-map-data/issues/123
[Minimap_WaypointCost_33536_32000_15.zip](https://github.com/tibiamaps/tibia-map-data/files/5945285/Minimap_WaypointCost_33536_32000_15.zip)

**Comment by mathiasbynens** [comment]
These are all identical to the current files we already have. So looks like no changes happened there 👍  Thanks for checking anyway!
