### ISSUE TITLE
Gray Island has been changed

### ISSUE THREAD

**Issue by LeeKunTibia** [tibiamaps/tibia-map-data#142]
Probably to remove the annoying diagonal movement we had to make when leaving Gray Island, CipSoft has removed a rock and extended the walkable area west of the stone pile of Gray Island.

[Gray Island.zip](https://github.com/tibiamaps/tibia-map-data/files/6064294/Gray.Island.zip)

**Comment by mathiasbynens** [comment]
Thanks!
