### ISSUE TITLE
Kilmaresh Bridge Changes

### ISSUE THREAD

**Issue by LeeKunTibia** [tibiamaps/tibia-map-data#147]
We never updated the second batch of changes to the Kilmaresh Bridges west of town, [here ](https://tibiamaps.io/map#33841,31514,7:2)and [here](https://tibiamaps.io/map#33791,31520,7:2). 

[Kilmaresh Bridges.zip](https://github.com/tibiamaps/tibia-map-data/files/6073720/Kilmaresh.Bridges.zip)

**Comment by mathiasbynens** [comment]
Thanks!
