### ISSUE TITLE
The map shows a place that doesn't exist.

### ISSUE THREAD

**Issue by AndrewX77** [tibiamaps/tibia-map-data#157]
There's something wrong with this area /map#32427,31888,9:3 like a duplication with this other area;
![Screenshot_2021-04-27 _](https://user-images.githubusercontent.com/83264582/116187771-721c8680-a726-11eb-98d2-ac3a39549021.jpg)

Actually this is how it looks;
![2021-04-27_052508569_Akaneir_Hotkey](https://user-images.githubusercontent.com/83264582/116186342-b78b8480-a723-11eb-8a8a-4e9e5145896e.png)

**Comment by LeeKunTibia** [comment]
This is a case of an Odyssey bug. Here are the updated files:

[Dwarf Mines Odyssey.zip](https://github.com/tibiamaps/tibia-map-data/files/6610321/Dwarf.Mines.Odyssey.zip)
