### ISSUE TITLE
10.94 update (Summer Update 2016)

### ISSUE THREAD

**Issue by mathiasbynens** [tibiamaps/tibia-map-data#16]
- [ ] Explore Otherworld dungeons as part of the Heart of Destruction quest
    - [x] through Svargrond vortex (partially done in 5d89ba67a2bf683145f52334da14c2063c474146 and completed in caa814d650e91791e367c031b2ccd1086e8aaa62)
    - [x] boss area through Svargrond vortex ([ref.](http://tibiawiki.com.br/wiki/Heart_of_Destruction_Quest); done in d977968e4081b08819823bd497418853378664a7)
    - [x] through Zao vortex (caa814d650e91791e367c031b2ccd1086e8aaa62; same dungeon as Svargrond with one variation)
    - [x] boss area through Zao vortex ([ref.](http://tibiawiki.com.br/wiki/Heart_of_Destruction_Quest); done in 71fe7fe3558d633455c305f55cf70f2a906870c7)
    - [x] through Ankrahmun vortex (same dungeon as Svargrond)
    - [x] boss area through Ankrahmun vortex ([ref.](http://tibiawiki.com.br/wiki/Heart_of_Destruction_Quest); done in 728dac8949db07924c75a4865e077a8bbf27f153)
    - [x] through Edron vortex (fully mapped in caa814d650e91791e367c031b2ccd1086e8aaa62; this is a separate dungeon)
    - [x] through vortex south of the Dwarf Bridge ([ref.](http://forum.portaltibia.com.br/topic/32845-summer-update-2016-screenshots/page-2#entry559659); fully mapped in fda07a1fecd66f22c8723dbfee18713ed1c284c6)
    - [x] fourth and fifth boss ([ref.](http://forum.test.tibia.com/forum/?action=thread&threadid=200&postid=11118#post11118); done in 20f1a877df5ecb64cbb82b8e690a4de246f7cd9b)
    - [x] Heart of Destruction area itself (final boss; done in 8fd526e19000d9ad20643f6f65c10e39829033f3)
- [x] Explore PvE arenas
    - [x] Thais
    - [x] Edron (open as of http://forum.test.tibia.com/forum/?action=thread&threadid=198&postid=11099#post11099) (done in 9fa0ba42ea4cb1d2a64dd7bc9b2ce91ca0cfd328)
    - [x] Rathleton (open as of http://forum.test.tibia.com/forum/?action=thread&threadid=198&postid=11325#post11325; done in 55e28a0955e9adb33d7b52b9da14672f92563018)
    - [x] Ankrahmun (open as of http://forum.test.tibia.com/forum/?action=thread&threadid=198&postid=11325#post11325; done in 9d2bfdda892116a4c1020973d8c086a702b76934)
    - [x] Kazordoon (open as of http://forum.test.tibia.com/forum/?action=thread&threadid=198&postid=11336#post11336; done in 9d2bfdda892116a4c1020973d8c086a702b76934)

- [x] [new vortex entrances as of April 27th](http://forum.test.tibia.com/forum/?action=thread&threadid=200&postid=11019#post11019)
    - [x] Svargrond (done in e378314050e2b980fbc916323836c8e5d38c4aec)
    - [x] Edron (done in bdb482aa865ff03930f49f3c2340b986bca3ef0b)
    - [x] Zao (done in cc8e363300fe2e35e745d4d746418e08f2dd53bf)
    - [x] Ankrahmun (done in 4f0e738c1a653f9f182d686161d8275ab624498f)
    - [x] Kazordoon (unchanged)

**Comment by benjaminkomen** [comment]
I wanted to complain maps are missing on the otherworld, but I see you haven't finished mapping yet.

**Comment by mathiasbynens** [comment]
@benjaminkomen If you know anyone with complete maps of this area, or if you know of any TibiaCast recordings that explore the area more fully, let me know!

**Comment by benjaminkomen** [comment]
If you simply <a href="https://www.tibiacast.com/recordings?sort=date&cutoff=all&search=heart+of+destruction">search for heart of destruction</a> on tibiacast, you will find some. The 47 minutes one from Oriibz has some boss rooms and the rooms before the boss rooms with the lever. Then there are several casts of the final boss rooms. I can make png files of the area, but I guess you have better extraction and merge tools.

**Comment by mathiasbynens** [comment]
@benjaminkomen Thanks; I’ve played `tibiacast:recording:3691343` which mapped the Eradicator and Outburst boss rooms. 20f1a87

Let me know if you find a cam for the final boss room.

**Comment by mathiasbynens** [comment]
> Let me know if you find a cam for the final boss room.

`tibiacast:recording:3705640` by Octuous seems to map it.

**Comment by mathiasbynens** [comment]
* Outburst boss room: https://tibiamaps.io/map#32235,31284,14
* Eradicator boss room: https://tibiamaps.io/map#32309,31284,14

**Comment by mathiasbynens** [comment]
The final boss room is missing a small section on the western side: https://tibiamaps.io/map#32270,31349,14:2 Let me know if you find a recording that explores it.
