### ISSUE TITLE
Re-exploring Underwater Paths

### ISSUE THREAD

**Issue by LeeKunTibia** [tibiamaps/tibia-map-data#161]
Now that #158 is fixed, we can re-explore all Underwater areas so their pathfinding is not 'corrupted' during processing. 

- [x] ~~Calassa~~ Fixed with #61 
- [x] Both Svargrond Sea Serpents
- [x] Sunken Quarter
- [x] Liberty Bay Quaras
- [x] Port Hope Quara/Water Elemental caves
- [x] ~~Fiehonja? (this area is special)~~ (not really underwater, different path color)
- [x] Frozen Trench
- [x] Drefia underwater room
- [x] Krailos underwater area
- [x] Seacrest Grounds

**Comment by LeeKunTibia** [comment]
First batch:

[Sunken Quarter.zip](https://github.com/tibiamaps/tibia-map-data/files/6641771/Sunken.Quarter.zip)
[Sea Serpent Area.zip](https://github.com/tibiamaps/tibia-map-data/files/6641772/Sea.Serpent.Area.zip)
[Frozen Trench.zip](https://github.com/tibiamaps/tibia-map-data/files/6641773/Frozen.Trench.zip)

**Comment by LeeKunTibia** [comment]
A few more:

[Krailos and Drefia Underwater.zip](https://github.com/tibiamaps/tibia-map-data/files/6642779/Krailos.and.Drefia.Underwater.zip)
[PH and LB Underwater.zip](https://github.com/tibiamaps/tibia-map-data/files/6642780/PH.and.LB.Underwater.zip)

Seacrest grounds is trickier. It's actually not full-yellow because it's newer, but it's path wasn't perfect idea, with some missing parts. I'm exploring those and painting other parts manually, but there's one [area](https://tibiamaps.io/map#33545,31855,15:0)I still haven't figured out how to reach.

**Comment by LeeKunTibia** [comment]
Finally! Figured out how to reach that area. There is one specific tile where you have to levitate up, [here](https://tibiamaps.io/map#33538,31808,15:2). I'll add a marker after I sync again. 

[Seacrest Grounds.zip](https://github.com/tibiamaps/tibia-map-data/files/6644791/Seacrest.Grounds.zip)

**Comment by LeeKunTibia** [comment]
Oh, I also explored Leviathan's room in Svargrond which was still missing: 
[Uploading Leviathan.zip…]()

**Comment by mathiasbynens** [comment]
> Please don't close this issue after merging this, I want to take a look at the files again and check if I missed anything.

Alright, I'll keep it open until you decide to close it :)
