### ISSUE TITLE
Yasir Ankrahmun Ship + Missing Part in Kazordoon

### ISSUE THREAD

**Issue by Hunter-of-Dragoes** [tibiamaps/tibia-map-data#162]
Since I noticed it wasn't fully explored, I re-explored Yasir ship in Ankrahmun (2 affected floors):
[Yasir Ankrahmun Ship.zip](https://github.com/tibiamaps/tibia-map-data/files/6643166/Yasir.Ankrahmun.Ship.zip)

I noticed the room next to Kazordoon's throne room was slightly changed (3 floors affected):
[Yasir Ankrahmun Ship.zip](https://github.com/tibiamaps/tibia-map-data/files/6643167/Yasir.Ankrahmun.Ship.zip)

**Comment by mathiasbynens** [comment]
I think you uploaded the same ZIP twice by accident. Do you still have the Kazordoon throne room files?

**Comment by Hunter-of-Dragoes** [comment]
Oops, sorry 'bout that!

Here's the correct ZIP:
[Kaz Missing Part.zip](https://github.com/tibiamaps/tibia-map-data/files/6644698/Kaz.Missing.Part.zip)

**Comment by mathiasbynens** [comment]
Thanks!
