### ISSUE TITLE
Drefia changes?

### ISSUE THREAD

**Issue by muriloricci** [tibiamaps/tibia-map-data#165]
Hey, I decided doing the Gravedigger quest with my character and noticed some minor changes to my minimap while doing it. I reinstalled minimaps from TibiaMaps and walked around a bit and here are some changes to the map.

Not sure if CipSoft updated it with Summer Update or TibiaMaps had them wrong but weird nonetheless. Anyways.

[Drefia.zip](https://github.com/tibiamaps/tibia-map-data/files/6851883/Drefia.zip)

**Comment by muriloricci** [comment]
Sorry, you can actually add this one on top of the previously sent file since I explored a room a bit better.

[Drefia 2.zip](https://github.com/tibiamaps/tibia-map-data/files/6854837/Drefia.2.zip)

**Comment by mathiasbynens** [comment]
Thanks!
