### ISSUE TITLE
Explore borders around Last Lore Keeper rooms

### ISSUE THREAD

**Issue by LeeKunTibia** [tibiamaps/tibia-map-data#168]
[Last Lore Keeper.zip](https://github.com/tibiamaps/tibia-map-data/files/7022628/Last.Lore.Keeper.zip)

The borders around The Last Lore Keeper [rooms](https://tibiamaps.io/map#31986,32848,14:1) were not fully explored.

**Comment by mathiasbynens** [comment]
Thanks!
