### ISSUE TITLE
Fix Oramond Hydras

### ISSUE THREAD

**Issue by LeeKunTibia** [tibiamaps/tibia-map-data#170]
I found a few wrong tiles on the map of [Oramond's Hydras](https://tibiamaps.io/map#33498,31951,9:0). Not sure if they're Odyssey artefacts, if the map changed or something else. Either way:

[Oramond Hydras.zip](https://github.com/tibiamaps/tibia-map-data/files/7026472/Oramond.Hydras.zip)

**Comment by mathiasbynens** [comment]
Thanks!
