### ISSUE TITLE
Endurance Mission path 

### ISSUE THREAD

**Issue by LeeKunTibia** [tibiamaps/tibia-map-data#172]
I was testing one of the slowest possible floors we can easily reach and discovered our path data for the Bigfoot's Burden Endurance mission [area](https://tibiamaps.io/map#32750,31799,11:2) is wrong/outdated. The northern part of the map is very slow and has a different path color.

[Minimap_WaypointCost_32512_31744_11.zip](https://github.com/tibiamaps/tibia-map-data/files/7230559/Minimap_WaypointCost_32512_31744_11.zip)

**Comment by mathiasbynens** [comment]
Thanks!
