### ISSUE TITLE
Tibia Museum expansion

### ISSUE THREAD

**Issue by muriloricci** [tibiamaps/tibia-map-data#177]
After the latest fansite items the museum was slightly expanded. :)

[Tibia Museum Expansion.zip](https://github.com/tibiamaps/tibia-map-data/files/7533753/Tibia.Museum.Expansion.zip)

**Comment by muriloricci** [comment]
Oops, forgot the waypoints.

[Tibia Museum Expansion + Waypoints.zip](https://github.com/tibiamaps/tibia-map-data/files/7533822/Tibia.Museum.Expansion.%2B.Waypoints.zip)

**Comment by mathiasbynens** [comment]
Thanks!
