### ISSUE TITLE
Winter Update 2021 - Tibia 12.80

### ISSUE THREAD

**Issue by muriloricci** [tibiamaps/tibia-map-data#179]
The update is not out yet but I've updated the Adventurer's Guild minimap (not the waypoint costs though) according to the image provided by CipSoft.

[Minimap_Color_32000_32256_7.zip](https://github.com/tibiamaps/tibia-map-data/files/7588278/Minimap_Color_32000_32256_7.zip)

**Comment by mathiasbynens** [comment]
Thanks! Let’s keep the issue open as a reminder to get the waypoint costs once we can.

**Comment by muriloricci** [comment]
There we go.

[Minimap_WaypointCost_32000_32256_7.zip](https://github.com/tibiamaps/tibia-map-data/files/7617366/Minimap_WaypointCost_32000_32256_7.zip)

**Comment by muriloricci** [comment]
There we go.

[Exalted Forge + WaypointCost.zip](https://github.com/tibiamaps/tibia-map-data/files/7617375/Exalted.Forge.%2B.WaypointCost.zip)

**Comment by mathiasbynens** [comment]
Thank you!
