### ISSUE TITLE
Are floors obsolet?

### ISSUE THREAD

**Issue by lucasmonstro** [tibiamaps/tibia-map-data#180]
Hello, trying to know from where you guys get the minimap content. I'm asking because Im walking in ot 12.64 and I can see a lot off mini pixels dead or some zones that are very different. Can you guys explain me it? Thanks

**Comment by mathiasbynens** [comment]
OT servers have their own map which may or may not match the real Tibia map. This project only applies to the real Tibia map.

**Comment by lucasmonstro** [comment]
Big thanks <3
