### ISSUE TITLE
Knightwatch Tower duplicate minimap

### ISSUE THREAD

**Issue by Nohus** [tibiamaps/tibia-map-data#183]
There is a glitch on the map here: https://tibiamaps.io/map#32819,32357,4:2
And other floors nearby.

**Comment by muriloricci** [comment]
I don't know if there's a historical reason for this but I fixed the files.
[minimap knightwatch tower.zip](https://github.com/tibiamaps/tibia-map-data/files/7933307/minimap.knightwatch.tower.zip)

**Comment by LeeKunTibia** [comment]
For the record, this is the same as the issues here: #65 .

**Comment by mathiasbynens** [comment]
Thanks, everyone!
