### ISSUE TITLE
Tibia's 25th Anniversary

### ISSUE THREAD

**Issue by muriloricci** [tibiamaps/tibia-map-data#184]
[25 Anniversary + Some bosses.zip](https://github.com/tibiamaps/tibia-map-data/files/7828566/25.Anniversary.%2B.Some.bosses.zip)

**Comment by mathiasbynens** [comment]
[`additional-portals.zip`](https://github.com/tibiamaps/tibia-map-data/files/7830027/additional-portals.zip)

**Comment by LeeKunTibia** [comment]
Here are some more parts of the dungeon.

[Time Traveller Dungeon.zip](https://github.com/tibiamaps/tibia-map-data/files/7830721/Time.Traveller.Dungeon.zip)

**Comment by mathiasbynens** [comment]
[`baby-seal-floor.zip`](https://github.com/tibiamaps/tibia-map-data/files/7830887/baby-seal-floor.zip)

**Comment by mathiasbynens** [comment]
[`hydra-floor-improved.zip`](https://github.com/tibiamaps/tibia-map-data/files/7830910/hydra-floor-improved.zip)

**Comment by mathiasbynens** [comment]
[`after-hydra-floor-slight-improvements.zip`](https://github.com/tibiamaps/tibia-map-data/files/7830921/after-hydra-floor-slight-improvements.zip)

**Comment by mathiasbynens** [comment]
Thanks for the help so far, everyone! I'm pushing all the changes we've collected so far now. Please re-sync once the downloads are updated (i.e. in ~15 minutes).

**Comment by mathiasbynens** [comment]
[`improvements.zip`](https://github.com/tibiamaps/tibia-map-data/files/7831681/improvements.zip)

**Comment by LeeKunTibia** [comment]
Addition to the missing/incomplete boss rooms.

Still missing some rooms of the Lord Retro fight and fully exploring the Tentugly-like room.

[Minimap_WaypointCost_33536_30976_15.zip](https://github.com/tibiamaps/tibia-map-data/files/7832455/Minimap_WaypointCost_33536_30976_15.zip)

**Comment by mathiasbynens** [comment]
Note to self: the fun fair in Carlin and Edron is still missing. Also, I should go check the Edron circle.

**Comment by muriloricci** [comment]
Some improvements to a Anniversary boss room and all Lord Retro rooms.
[minimap final.zip](https://github.com/tibiamaps/tibia-map-data/files/7836283/minimap.final.zip)

And all Lucky Dragon minigame areas.
[minimap lucky dragon.zip](https://github.com/tibiamaps/tibia-map-data/files/7836330/minimap.lucky.dragon.zip)

**Comment by muriloricci** [comment]
Oh yeah, kind of forgot this new pixel change for Morshabaal's crystal.
[minimap morshabaal.zip](https://github.com/tibiamaps/tibia-map-data/files/7836350/minimap.morshabaal.zip)

**Comment by LeeKunTibia** [comment]
> Note to self: the fun fair in Carlin and Edron is still missing. Also, I should go check the Edron circle.

They'll be gone after the event is over, though. Are these maps really necessary? They should be reverted back to the regular areas after the event is over, so I can only see them being useful here for historical record.

**Comment by mathiasbynens** [comment]
> > Note to self: the fun fair in Carlin and Edron is still missing. Also, I should go check the Edron circle.
> 
> They'll be gone after the event is over, though. Are these maps really necessary? They should be reverted back to the regular areas after the event is over, so I can only see them being useful here for historical record.

I agree with you. I would like to have a revision of the map data with these areas explored, but there's no point in keeping them forever.

**Comment by mathiasbynens** [comment]
Posted #185 to track the Morshabaal area maps, since those might be harder to get than everything else.

**Comment by LeeKunTibia** [comment]
I noticed there are still 2 rooms (King Tibianis and Tentugly) missing corners. Here they are:
[Minimap_Color_33536_30976_15.zip](https://github.com/tibiamaps/tibia-map-data/files/7843672/Minimap_Color_33536_30976_15.zip)

**Comment by LeeKunTibia** [comment]
Looks like CipSoft also changed the areas where the event raids appear, at least in Tiquanda, by removing part of the plants to make the area easier to move around:

![image](https://user-images.githubusercontent.com/31053487/149544663-68343582-96ab-4ae5-b67a-0fb640ad2e60.png)

I suppose they'll also revert these (specially because now there are floating bamboo leaves on the upper floor...), but here are the files for the record.

[Tiquanda.zip](https://github.com/tibiamaps/tibia-map-data/files/7871580/Tiquanda.zip)

**Comment by mathiasbynens** [comment]
Here we go again... Enabling the Orcsoberfest maps (d5af2f372b72f65638397a70222cb6bab5017a57) has removed parts of the new Retro quest areas. We'll need to update the Orcsoberfest pack adding the new areas.

**Comment by mathiasbynens** [comment]
> Should the temporary changes be reverted/re-explored? Funfairs, changes in Tiquanda, changes near Edron Funfair.

Yeah, I guess so.

**Comment by muriloricci** [comment]
I've noticed the Lucky Dragon areas are still displayed on the live version of the map. Is that intentional?

**Comment by mathiasbynens** [comment]
> I've noticed the Lucky Dragon areas are still displayed on the live version of the map. Is that intentional?

Not intentional. We just haven't gotten around to re-exploring/removing them.

**Comment by muriloricci** [comment]
This should fix it.
[minimap thaiscarlinedron.zip](https://github.com/tibiamaps/tibia-map-data/files/9092010/minimap.thaiscarlinedron.zip)

**Comment by mathiasbynens** [comment]
> This should fix it. [minimap thaiscarlinedron.zip](https://github.com/tibiamaps/tibia-map-data/files/9092010/minimap.thaiscarlinedron.zip)

Thanks! Merged.
