### ISSUE TITLE
Secret hard cave

### ISSUE THREAD

**Issue by Gesiano9999** [tibiamaps/tibia-map-data#186]
Hello. When looking for fiendish monsters today, me and a friend have found a "Hard" monster in an unknown spot. We cannot reach him, but I do know his coordinates. It is located on -8 floor, northeast of cormaya steamboat and west of the middle maxxen teleport cave.

Screenshot: https://imgur.com/a/XmETlBu

![secret monster](https://user-images.githubusercontent.com/81942/150597404-4256e4e1-30f4-47fa-8fc8-b668ec0fda35.png)

Monster is teorically located on the exclamation mark.

**Comment by mathiasbynens** [comment]
For future reference, the marker is around here: https://tibiamaps.io/map#33343,31950,15:1 I have no idea which area that is but I'll ask around. Thanks for filing the issue. I hope we can figure this one out!

**Comment by mathiasbynens** [comment]
@Gesiano9999 I noticed you're a streamer (just followed you 👍) -- any chance you have a link to the timestamp where you `exiva` from these two spots (Cormaya boat + Maxxen dungeon)?

**Comment by Gesiano9999** [comment]
Sure. It's Dê uma olhada neste vídeo "ek 1372 kalibra "
https://www.twitch.tv/gesiian/v/1267794355?sr=a&t=6333s
1h44min to 1h:47min

Em sex., 21 de jan. de 2022 18:31, Mathias Bynens ***@***.***>
escreveu:

**Comment by Valendrop** [comment]
Hello, just to leave here an hypothesis.

Since I've saw an interview with Chayenne in the past, about the mechanics of the Zzaion Raid I guess that many places of the game works in the same way.

So, in the Hero of Rathleton Quest, just after this teleport (On the Maxxen's middle room) there is a room that shrinks in the time (Lava Room), this can be a mechanism activated in the same way that Chayenne said in the past to Zzaion, but instead of a rat/other creature they used an hard creature of the previous room, like Vulcongra, Hellfire Fighter or Lost Berserker.

Well, just a theory. :D

**Comment by mathiasbynens** [comment]
Someone who prefers to remain anonymous sent me the following:

![](https://user-images.githubusercontent.com/81942/150631943-03481a58-bf0d-4307-99f6-ccc429d85297.png)

The source of this is [the Tibia 7.7 leak](https://sammynsc.wordpress.com/2013/04/25/interview-with-dennis-aka-toor/). The reporter mentioned:

> This is from the leaked map files. This spot seem to be where the demons of parchment room wait before it's activated.

So supposedly there's 1 inaccessible demon in each of the four 1-sqm rooms. If this ever happens again, it might be fun to try [pulling the parchment](https://tibia.fandom.com/wiki/Parchment_Room_Quest/Spoiler) to see if that makes the fiendish demon accessible.

![](https://user-images.githubusercontent.com/81942/150632161-0c1dd973-7f42-4757-b9a7-bd6da5cea725.png)

**Comment by Gesiano9999** [comment]
Demons from parchment room seems to be the right answer so. If it spawn
again sure I can try this xD.

Em sáb., 22 de jan. de 2022 06:05, Mathias Bynens ***@***.***>
escreveu:

**Comment by Gesiano9999** [comment]
Just outside of the demons screaming range? I don't know the range but it
seems pretty close.

Em sáb., 22 de jan. de 2022 10:08, TheAntilu ***@***.***>
escreveu:

**Comment by mathiasbynens** [comment]
I've added the marker now.

If you mention this investigation on your stream, please share the clip :) Thanks for asking the question, I learned something new!
