### ISSUE TITLE
Fix/Improve Shadows of Yalahar Mission 12 area

### ISSUE THREAD

**Issue by LeeKunTibia** [tibiamaps/tibia-map-data#189]
I just did this mission and noticed we could improve some borders. Also, apparently something apparently changed [here](https://tibiamaps.io/map#32560,31242,13:2) because the map is slightly different "now". 
[Shadows 12.zip](https://github.com/tibiamaps/tibia-map-data/files/8058288/Shadows.12.zip)

**Comment by mathiasbynens** [comment]
Thanks!
