### ISSUE TITLE
Secret of Museum of Tibian Arts 

### ISSUE THREAD

**Issue by muriloricci** [tibiamaps/tibia-map-data#191]
Based on the information shared on a Tibia Secrets article (https://tibiasecrets.com/secret-of-the-museum-of-tibian-arts-revealed/) I have updated the minimaps related to this recently reached room.

[minimap mota.zip](https://github.com/tibiamaps/tibia-map-data/files/8152842/minimap.mota.zip)

**Comment by mathiasbynens** [comment]
Thanks!
