### ISSUE TITLE
Darashia Warzone Portal

### ISSUE THREAD

**Issue by muriloricci** [tibiamaps/tibia-map-data#192]
Recently someone found out it's possible to levitate in a specific spot and reach a "unreachable" tile next to Darashia's portal to Warzones. With that we got some additional pixels in the waypoint cost file for that area.

[minimap darashia portal.zip](https://github.com/tibiamaps/tibia-map-data/files/8254603/minimap.darashia.portal.zip)

You can see how to get there below:
https://user-images.githubusercontent.com/6180473/158408574-ead6d6bb-12c7-4c6a-8cf8-2442579db958.mp4
Location: https://tibiamaps.io/map#33192,32389,9:2

**Comment by mathiasbynens** [comment]
This is so cool. Thanks for including the video!
