### ISSUE TITLE
Update Astral Shaper Ruins

### ISSUE THREAD

**Issue by LeeKunTibia** [tibiamaps/tibia-map-data#194]
The map [here](https://tibiamaps.io/map#32778,32853,13:2) was changed. It used to be empty fields but looks like CipSoft filled it with invisible tiles, probably to prevent levitating from being possible to the floor below. 

[Servant Replicas.zip](https://github.com/tibiamaps/tibia-map-data/files/8359123/Servant.Replicas.zip)

**Comment by mathiasbynens** [comment]
Thanks!
