### ISSUE TITLE
Improve Claustrophobic Inferno

### ISSUE THREAD

**Issue by molx** [tibiamaps/tibia-map-data#195]
Some corners there could be improved. I also changed the 2nd raid to open because that's how you'll usually find it.

[Claustrophobic Inferno.zip](https://github.com/tibiamaps/tibia-map-data/files/8637263/Claustrophobic.Inferno.zip)

**Comment by mathiasbynens** [comment]
Not sure how this one slipped the cracks… It’s merged now. Thank you!
