### ISSUE TITLE
Pantibian Festival maps

### ISSUE THREAD

**Issue by mathiasbynens** [tibiamaps/tibia-map-data#197]
[Exarus](https://www.twitch.tv/exarus_) explored some (but not 100%) of the Pantibian Festival maps. If other streamers and participants can share their maps, I can write some code to merge all of them and get as much data as possible.

**Comment by muriloricci** [comment]
I just got this from a friend of mine. He said he got late to the event so he only got two obstacles explored.
[Pantibian - Gryllo.zip](https://github.com/tibiamaps/tibia-map-data/files/8720886/Pantibian.-.Gryllo.zip)

**Comment by LeeKunTibia** [comment]
I got one set from a friend and a streamer is going to send me his files to. The first set:

[Silerpali Pantibian Festival.zip](https://github.com/tibiamaps/tibia-map-data/files/8720908/Silerpali.Pantibian.Festival.zip)

**Comment by Hunter-of-Dragoes** [comment]
And I got these maps:
[minimap - Lejonhjartat.zip](https://github.com/tibiamaps/tibia-map-data/files/8720992/minimap.-.Lejonhjartat.zip)
I think I'll be able to get more maps, I'll share them once I get them. :)

**Comment by muriloricci** [comment]
More maps, this time from Skyzo.
[Minimap_-_Skyzo.zip](https://github.com/tibiamaps/tibia-map-data/files/8721142/Minimap_-_Skyzo.zip)

**Comment by Exarus42** [comment]
A map fromt he event for my dear friend
[minimap.zip](https://github.com/tibiamaps/tibia-map-data/files/8721250/minimap.zip)

**Comment by muriloricci** [comment]
Maps from Dark Black Magician.
[Minimap - DBM.zip](https://github.com/tibiamaps/tibia-map-data/files/8721327/Minimap.-.DBM.zip)

**Comment by Hunter-of-Dragoes** [comment]
More maps from the Pantibian Festival:
[minimap - Core.zip](https://github.com/tibiamaps/tibia-map-data/files/8730345/minimap.-.Core.zip)

**Comment by muriloricci** [comment]
Pantibian Final v1 (https://github.com/tibiamaps/tibia-map-data/issues/197#issuecomment-1131705197) + Sasch files
[Pantibian Final v2.zip](https://github.com/tibiamaps/tibia-map-data/files/8730831/Pantibian.Final.v2.zip)

**Comment by Hunter-of-Dragoes** [comment]
And more maps from the Pantibian Festival:
[minimap - Itexo.zip](https://github.com/tibiamaps/tibia-map-data/files/8734735/minimap.-.Itexo.zip)

**Comment by muriloricci** [comment]
> And more maps from the Pantibian Festival: [minimap - Itexo.zip](https://github.com/tibiamaps/tibia-map-data/files/8734735/minimap.-.Itexo.zip)

Unfortunately no new pixels from Itexo's files.
