### ISSUE TITLE
Map unexplorable areas from CipSoft screenshots

### ISSUE THREAD

**Issue by mathiasbynens** [tibiamaps/tibia-map-data#20]
At least 3 screenshots on https://secure.tibia.com/news/?subtopic=newsarchive&id=1975 show maps for unexplorable areas.

1. ![fa_feb2010_1](https://cloud.githubusercontent.com/assets/81942/17996400/eb9c787a-6b68-11e6-94ec-dd1d6d1a11ff.jpg)
2. ![fa_feb2010_2](https://cloud.githubusercontent.com/assets/81942/17996404/eba05bca-6b68-11e6-9e10-a3242f96f94c.jpg)
3. ![fa_feb2010_3](https://cloud.githubusercontent.com/assets/81942/17996405/eba08172-6b68-11e6-89eb-b4558617bd47.jpg)
4. ![fa_feb2010_4](https://cloud.githubusercontent.com/assets/81942/17996403/eba057ec-6b68-11e6-8e2b-a848c5a3f212.jpg)
5. ![fa_feb2010_5](https://cloud.githubusercontent.com/assets/81942/17996401/eb9f9cda-6b68-11e6-83e2-fb76feda6cdd.jpg)
6. ![fa_feb2010_6](https://cloud.githubusercontent.com/assets/81942/17996402/eb9f8614-6b68-11e6-98b6-6869979df39a.jpg)
7. ![fa_feb2010_7](https://cloud.githubusercontent.com/assets/81942/17996406/ebb3cbba-6b68-11e6-8458-2a0b03870163.jpg)

**Comment by Hunter-of-Dragoes** [comment]
Pay attention to white pixels, they are not part of the map! I think they represent monster homes (spawn locations).

Third Screenshot
4 fields here: https://tibiamaps.io/map#32169,32278,8:1
And you can confirm the secret cave here: https://tibiamaps.io/map#32075,32280,8:1

Fourth Screenshot
Mountain around cave: https://tibiamaps.io/map#33346,31882,9:1
You can also take it from here: http://vignette2.wikia.nocookie.net/tibia/images/e/e6/Minimap_Floor_9.png/revision/latest?cb=20160104064254&path-prefix=en

Fifth Screenshot
Cave walls: https://tibiamaps.io/map#32670,32892,10:1

Sixth Screenshot
???

Seventh Screenshot
Moutain around caves + north part of Frankenstein's cave + narrow passage on northeast: https://tibiamaps.io/map#32896,31276,11:1
You can also take it from here: http://vignette2.wikia.nocookie.net/tibia/images/e/e4/Minimap_Floor_11.png/revision/latest?cb=20160104064333&path-prefix=en

**Comment by mathiasbynens** [comment]
The sixth screenshot is this area: https://tibiamaps.io/map#32048,32971,8:1. We could add the extra walls but I don’t think it’s really that helpful.

**Comment by Hunter-of-Dragoes** [comment]
Brown mountain around this cave is mixed with grey pixels: https://tibiamaps.io/map#33346,31882,9:1

**Comment by mathiasbynens** [comment]
I’ve added the four fields @Hunter-of-Dragoes mentioned in https://github.com/tibiamaps/tibia-map-data/issues/20#issuecomment-255635351 to the map data. I had to guess the location to some extent.
