### ISSUE TITLE
new POI's for Zao

### ISSUE THREAD

**Issue by Spence28** [tibiamaps/tibia-map-data#208]
Vengoth, Orc Settlement and more
[minimapmarkers.zip](https://github.com/tibiamaps/tibia-map-data/files/9541455/minimapmarkers.zip)

**Comment by mgis90** [comment]
I want to contribute but how do I do this?
I have Muggy Plains, Spirittrails, also I had some other areas marked with POIs but now I dont know how to diff them.
Dragonblaze Peaks were missing and I marked them one time. 2 tries.
I had Okolnir or some other icy island which was missing in the downloadable mapswithmarkers.
I'm not sure which file is Okolnir in, as I was swapping between my maps and public.
[markers-muggyplains-spirittrails.zip](https://github.com/tibiamaps/tibia-map-data/files/9647273/markers-muggyplains-spirittrails.zip)

**Comment by rmobis** [comment]
@mgis90 If you open a new issue with the .zip, I'll setup a PR so your markers are added.
