### ISSUE TITLE
Tunnel in Yalahar sewers leading to tavern cellar

### ISSUE THREAD

**Issue by puddyput** [tibiamaps/tibia-map-data#21]
Use pickaxe here
http://tibia.wikia.com/wiki/Mapper?coords=128.35-122.27-8-4-1-1

![image](https://cloud.githubusercontent.com/assets/6353828/18232418/705acc3e-72cf-11e6-9ade-c779c36de152.png)

**Comment by mathiasbynens** [comment]
@puddyput I tried using a whacking driller of fate (which acts as a pick) on all the stone piles I could see there, to no avail. I also tried to use a regular pick — same result. Am I missing something?

![](https://cloud.githubusercontent.com/assets/81942/18238930/c501d954-7341-11e6-9909-e95e41ef1932.png)

**Comment by puddyput** [comment]
Interesting.. Maybe it only works while you have the quest active. 
http://tibia.wikia.com/wiki/Top_of_the_City_Quest/Spoiler
its a shame Tibiacast was not working when I did it, I would have recordet it myself :/

**Comment by mathiasbynens** [comment]
The relevant map file would be `12812209.map`.

Thanks for pointing me to the quest. I’ll give it a try soon!

**Comment by puddyput** [comment]
Thanks! Enjoy the quest :)
For whatever reason github says my .map file in a zip container is an invalid file type. so I uploaded it somewhere else.
http://fication.org/12812209.map
