### ISSUE TITLE
POIs Muggy Plains, Spirittrails, Okolnir

### ISSUE THREAD

**Issue by mgis90** [tibiamaps/tibia-map-data#214]
This is somewhat related to issue 208.
New points of interest marked.

[markers-muggyplains-spirittrails.zip](https://github.com/tibiamaps/tibia-map-data/files/9659142/markers-muggyplains-spirittrails.zip)

[reference](https://github.com/tibiamaps/tibia-map-data/issues/208#issuecomment-1258157756)

**Comment by mathiasbynens** [comment]
Thanks!
