### ISSUE TITLE
Secret room in Banuta

### ISSUE THREAD

**Issue by mallikar** [tibiamaps/tibia-map-data#22]
My first time on GitHub so I don't know how to upload maps here, but let me know how I can help =)

![map](https://cloud.githubusercontent.com/assets/22874881/19421098/e94863be-93f8-11e6-8700-df011190d3bb.png)

**Comment by mathiasbynens** [comment]
@mallikar Thanks for filing this issue!

I’ll test this on a secondary char, since my main character has completed the Treasure Hunt Quest already. 

Btw, http://tibia.wikia.com/wiki/Treasure_Hunt_Quest/Spoiler#Mission_1 doesn’t mention this at all, so it will have to be updated once this is confirmed.

**Comment by mallikar** [comment]
@mathiasbynens  No problem :) Yes, I find it weird that nothing is mentioned about this on any wiki. It is a great spot for PvP, but lately more and more people has found out about this place so it might as well become public info now

**Comment by benjaminkomen** [comment]
I remember this from the test server when this quest came out. There is a poem which mentions that you have to dig 34 steps west of a tree with a mark. Since there are 3 trees in the jungle, there are 3 rooms. Two of them are not needed, one of them is needed to progress in the quest.

**Comment by mathiasbynens** [comment]
@benjaminkomen Do you know where the other tree, or — even better — the other pick / shovel tile is?

**Comment by benjaminkomen** [comment]
I made a wiki article about this tree: http://tibia.wikia.com/wiki/Giant_Tree_(Carving). The caves are always 17 squares west of the trees, for the second one I have a minimap: 
![location](https://cloud.githubusercontent.com/assets/12815582/19455376/1d241bf0-94bd-11e6-817f-3dd7b551084e.png) but unfortunately not for the other ones.
