### ISSUE TITLE
Some Carlin Surroundings and Field of Glory PoIs

### ISSUE THREAD

**Issue by muriloricci** [tibiamaps/tibia-map-data#221]
[minimapmarkers.zip](https://github.com/tibiamaps/tibia-map-data/files/9711772/minimapmarkers.zip)

**Comment by mathiasbynens** [comment]
This looks like it needs to be rebased, or otherwise filtered to only consider the newly added markers (and not remove any). @rmobis, IIRC you were working on something to make this easier, right? What's the status on that?

**Comment by rmobis** [comment]
@mathiasbynens  I've opened [tibia-maps-script#26](https://github.com/tibiamaps/tibia-maps-script/issues/26) which could help alleviate this issue, but since it got no response I wasn't sure whether to progress further. If that's something you feel would be a good addition, please let me know.

**Comment by mathiasbynens** [comment]
Apologies for dropping the ball there. I just responded to that issue. Would be amazing to have `--union` implemented as a first step! And yes, the GitHub bot idea is neat too :)

**Comment by muriloricci** [comment]
Can this be closed?

**Comment by rmobis** [comment]
@muriloricci Sadly, no. We're waiting on the development of a new feature in the tibia-maps-scripts repo to allow us to easily import those, as they were made with outdated markers. I've been kinda stalling to finish that though, but I'll try and do it this weekend.

**Comment by mathiasbynens** [comment]
@rmobis Any updates? :)

**Comment by rmobis** [comment]
@mathiasbynens thanks for friendly poke, it push me to finally get it done. I've opened PR https://github.com/tibiamaps/tibia-maps-script/pull/28

**Comment by mathiasbynens** [comment]
🥳
