### ISSUE TITLE
Map change in Edron Hero Cave

### ISSUE THREAD

**Issue by benjaminkomen** [tibiamaps/tibia-map-data#23]
There is a small change which happened in the Edron Hero cave. The teleporter seen here: http://tibia.wikia.com/wiki/Mapper?coords=129.175-123.186-14-2-1-1 / https://tibiamaps.io/map#33192,31670,14:2 has been moved to another room to the left. The minimap at this position now looks like this: 
![new minimap](https://cloud.githubusercontent.com/assets/12815582/19597233/a6d27076-9793-11e6-9c1d-6605bb3933ea.png)

**Comment by mathiasbynens** [comment]
The teleport has been removed. @benjaminkomen Can you confirm/deny if the maps contains the teleport at the new location? If not, how do I reach it?

**Comment by benjaminkomen** [comment]
Forgot to say, the new location is here: https://tibiamaps.io/map#33162,31650,13:2. In other words, it's already included in the maps.
