### ISSUE TITLE
New dire penguin location?

### ISSUE THREAD

**Issue by muriloricci** [tibiamaps/tibia-map-data#239]
A member of TibiaWiki Discord mentioned they found a dire penguin in a location not registered on the wiki nor TibiaMaps has a mark for it.

I've checked it a couple times but couldn't find it yet.

The location is around here: https://tibiamaps.io/map#31996,31176,7:2

**Comment by mathiasbynens** [comment]
😱

**Comment by muriloricci** [comment]
It's accurate, I just manage to find it there. :)

![2023-01-23_230039065_Picture_Hotkey](https://user-images.githubusercontent.com/6180473/214161520-8aa57061-f038-4303-8e71-07b9b91a14a9.png)

**Comment by mathiasbynens** [comment]
Incredible find! Nice to have it confirmed. So just to confirm, the marker location should be: https://tibiamaps.io/map#31996,31176,7:2 Correct?

**Comment by mathiasbynens** [comment]
In the screenshot it looks like you're closer to here: https://tibiamaps.io/map#31986,31181,7:2

**Comment by mathiasbynens** [comment]
Ok, added!
