### ISSUE TITLE
New points of interest

### ISSUE THREAD

**Issue by kinosei** [tibiamaps/tibia-map-data#240]
Hello, I discovered some points of interest that are not on the maps:

Thais Troll Caves:
- X: 32511 Y: 32279 Z: 6
- X: 32486 Y: 32292 Z: 7
- X: 32484 Y: 32289 Z: 7
- X: 32469 Y: 32275 Z: 8
- X: 32506 Y: 32237 Z: 10
- X: 32494 Y: 32245 Z: 10

Fibula:
- X: 32207 Y: 32371 Z: 10
- X: 32165 Y: 32419 Z: 7

Thais Surroundings:
- X: 32506 Y: 32153 Z: 7

Mount Sternun:
- X: 32475 Y: 32099 Z: 8
- X: 32436 Y: 32018 Z: 8

Carlin:
- X:32367  Y: 31767 Z: 6
- X:32386  Y: 31803 Z: 7
- X:32346  Y: 31836 Z: 7
- X:32339  Y: 31820 Z: 7

Carlin Surroundings:
- X:32421  Y: 31749 Z: 7
- X:32460  Y: 31785 Z: 7
- X:32383  Y: 31752 Z: 7
- X:32376  Y: 31742 Z: 7
- X:32360  Y: 31734 Z: 7
- X:32285  Y: 31649 Z: 7

Senja:
- X:32145  Y: 31670 Z: 7
- X:32164  Y: 31630 Z: 8
- X:32169  Y: 31629 Z: 7
- X:32171  Y: 31623 Z: 7
- X:32179  Y: 31638 Z: 7

Folda:
- X:32044 Y: 31524 Z: 7
- X:31996 Y: 31586 Z: 7

**Comment by mathiasbynens** [comment]
Thanks! Added.
