### ISSUE TITLE
Barbaria minimap mark

### ISSUE THREAD

**Issue by muriloricci** [tibiamaps/tibia-map-data#247]
I suggest a change to Barbaria's mark from the current one to the one selected in the image bellow. My boss hunting group has found about 5 Barbarias on that spot, never on to current mark.

![image](https://user-images.githubusercontent.com/6180473/218116877-af01aab2-a023-4aee-acc5-255d090b8c1c.png)

Opening this issue as I'm not entirely sure Barbaria would never spawn where the current mark is.

**Comment by muriloricci** [comment]
Updated here along with additional markers for Iksupan: https://github.com/tibiamaps/tibia-map-data/actions/runs/4203937664

**Comment by mathiasbynens** [comment]
41149c59ec63f7306ef61a82391bc723e3fa5266 Thanks!

My team did find Barbaria at least 2x on the old marker spot, but it's clear that we need to check the surrounding area anyhow, so I don't feel strongly about where the marker should be.
