### ISSUE TITLE
Safe spots idea - potential new feature?

### ISSUE THREAD

**Issue by muriloricci** [tibiamaps/tibia-map-data#248]
This is probably the craziest idea but I want to share it here nonetheless.

As a knight player myself, mostly a solo player, I often see myself in situations where I want to stand in specific tiles in a hunting spot; tiles where I can control the amount of creatures surrounding me and/or forcing them to stay diagonal from me to avoid beams and waves. Due to this, it's nice to know well the hunting spot you're hunting in order to optimise your hunt.

I have a friend who is also a knight, mostly hunting solo, and he is a big charm hunter. He spends hours and hours doing bestiary of different creatures, and during last rapid respawn event he was hunting infected weepers at the Warzone 2 area. He was standing in a tile here: https://tibiamaps.io/map#33061,31920,11:2. This tile has two unwalkable objects on its left and right side, so only 3 creatures can attack him at once on melee range.

We were talking and he invited me to join him but then we got ourselves in a situation where we couldn't use the same spot anymore, so we had to run the cave and and find something more suitable for a duo.

So here's the idea: would it be possible to use waypoint cost files to easily determine things like:
-  Where to stand in a hunting area if I only want 1~4 creatures attacking me? (I think 4 max is ideal since 5 creatures would be a wallbox and that would mean most spots in the hunting area)
- Where to stand in a hunting area if I want to 'wallbox' as a duo and only having creatures in front of me?

To make it a bit more visual, when toggling on the feature, you'd have visual indicators showing where you could stand while being surronding by X creatures (you could set the number of creatures varying from 1 to 4 as listed about). For example, this corner where you'd only be surrounded by 2 creatures (https://tibiamaps.io/map#33026,31923,11:4):
![image](https://user-images.githubusercontent.com/6180473/220227713-f4c68a14-c6af-43eb-998a-0d70213dd0c0.png)

I'm fully aware this is a crazy idea and likely hard to implement, potentially hard on a technical level as this could make this site slow when toggling on/off but just dropping the idea here. I believe this could be interesting not only for the situations listed before but in case you're hunting in a spot where you know at any moment things could go south and you need to adapt and run to a safer tile with less creatures, or maybe you have a PvP action and you need to protect yourself. You know, knowledge is power! :P

**Comment by mathiasbynens** [comment]
Interesting idea! It would take a bit of implementation work. Perhaps a simpler thing to implement that might still be helpful for your use case would be: adding the ability to press a button (or, say, the `P` key) to toggle between the map view and the pathfinding data for the current location on the map viewer. E.g. for your warzone example: https://tibiamaps.io/map#33060,31920,11:2

**Comment by mathiasbynens** [comment]
> Interesting idea! It would take a bit of implementation work. Perhaps a simpler thing to implement that might still be helpful for your use case would be: adding the ability to press a button (or, say, the `P` key) to toggle between the map view and the pathfinding data for the current location on the map viewer. E.g. for your warzone example: https://tibiamaps.io/map#33060,31920,11:2

This is now implemented. Check it out, and let me know if the pathfinding data seems useful enough to figure out these spots!

**Comment by LeeKunTibia** [comment]
> > Interesting idea! It would take a bit of implementation work. Perhaps a simpler thing to implement that might still be helpful for your use case would be: adding the ability to press a button (or, say, the `P` key) to toggle between the map view and the pathfinding data for the current location on the map viewer. E.g. for your warzone example: https://tibiamaps.io/map#33060,31920,11:2
> 
> This is now implemented. Check it out, and let me know if the pathfinding data seems useful enough to figure out these spots!

I don't know if I will ever use it but I like the idea of having that!

**Comment by muriloricci** [comment]
Indeed, that's a nice new feature! I'll close this issue as I'm happy with it even being different from my initial suggestion. :P

**Comment by mathiasbynens** [comment]
If you find any interesting spots like the ones you've already shared, please feel free to drop some links here or even add them as markers!

**Comment by mathiasbynens** [comment]
> > > Interesting idea! It would take a bit of implementation work. Perhaps a simpler thing to implement that might still be helpful for your use case would be: adding the ability to press a button (or, say, the `P` key) to toggle between the map view and the pathfinding data for the current location on the map viewer. E.g. for your warzone example: https://tibiamaps.io/map#33061,31920,11:2
> > 
> > 
> > This is now implemented. Check it out, and let me know if the pathfinding data seems useful enough to figure out these spots!
> 
> I don't know if I will ever use it but I like the idea of having that!

It might be useful to add functionality to display or log the friction value of the selected tile: https://github.com/tibiamaps/tibia-map/issues/51 For Part 2 of https://tibiald.com/2021/09/28/how-does-speed-work-in-tibia-1/ ;)
