### ISSUE TITLE
Other points of interests

### ISSUE THREAD

**Issue by kinosei** [tibiamaps/tibia-map-data#250]
Hello, I've been doing a lot of that lately, and I discovered yet some more new points of interest that are not on the maps:

Thais Troll Caves:
- X: 32511 Y: 32279 Z: 6
- X: 32486 Y: 32292 Z: 7
- X: 32484 Y: 32289 Z: 7
- X: 32469 Y: 32275 Z: 8
- X: 32506 Y: 32237 Z: 10
- X: 32494 Y: 32245 Z: 10

Folda:
- X:31978 Y: 31566 Z: 8
- X:31946 Y: 31631 Z: 8
- X:32177 Y: 31530 Z: 9
- X:32143 Y: 31552 Z: 9

Ghostlands:
- X:32178 Y: 31800 Z: 7
- X:32191 Y: 31787 Z: 7
- X:32201 Y: 31839 Z: 7
- X:32200 Y: 31798 Z: 9
- X:32181 Y: 31768 Z: 10
- X:32199 Y: 31865 Z: 9
- X:32171 Y: 31782 Z: 9
- X:32195 Y: 31804 Z: 9

Fields of Glory:
- X:32438 Y: 31641 Z: 7
- X:32450 Y: 31656 Z: 7
- X:32459 Y: 31693 Z: 7
- X:32473 Y: 31678 Z: 7

Vega
- X:31997 Y: 31684 Z: 7
- X:32003 Y: 31705 Z: 7
- X:31999 Y: 31711 Z: 7
- X:31955 Y: 31720 Z: 7
- X:31962 Y: 31700 Z: 7

Isle of Kings
- X:32173 Y: 31943 Z: 6

Ab'Dendriel Surroundings
- X:32527 Y: 31664 Z: 7
- X:32624 Y: 31735 Z: 7
- X:32672 Y: 31745 Z: 7

Ab'Dendriel
- X:32692 Y: 31656 Z: 6
- X:32657 Y: 31664 Z: 6
- X:32723 Y: 31616 Z: 7

Elvenbane
- X:32590 Y: 31647 Z: 8
- X:32592 Y: 31652 Z: 8
- X:32599 Y: 31642 Z: 8
- X:32595 Y: 31638 Z: 8
- X:32588 Y: 31638 Z: 9
- X:32581 Y: 31651 Z: 4
- X:32603 Y: 31639 Z: 7
- X:32580 Y: 31660 Z: 7

Venore Dragon Lair:
- X: 32816 Y: 32146 Z: 7
- X: 32804 Y: 32143 Z: 7

**Comment by mathiasbynens** [comment]
Woah, that’s quite the list! Thanks :) Added.
