### ISSUE TITLE
Fixing some issues and a few more tiles in Dawnport

### ISSUE THREAD

**Issue by muriloricci** [tibiamaps/tibia-map-data#251]
Fixing issues https://github.com/tibiamaps/tibia-map-data/issues/64 and https://github.com/tibiamaps/tibia-map-data/issues/78. I also got some extra tiles in Dawnport, in the orc dungeon.

[TibiaMaps Update February 28.zip](https://github.com/tibiamaps/tibia-map-data/files/10849788/TibiaMaps.Update.February.28.zip)

**Comment by mathiasbynens** [comment]
Thanks!
