### ISSUE TITLE
Gold Digger Achivment

### ISSUE THREAD

**Issue by EdMinatti** [tibiamaps/tibia-map-data#252]
A long time ago I had downloaded a version of your map that contained all the markers for the golddigger achievements in Ankrahmun. I lost minimapmarkers.bin with these points and never found it again. Do you not have it in the old files to make available to me? Thanks!

**Comment by mathiasbynens** [comment]
We have markers for them here: https://github.com/tibiamaps/tibia-map-data/blob/main/extra/achievements/markers.json

**Comment by mathiasbynens** [comment]
I’ve converted them into a `minimapmarkers.bin` file just for you: [`digging-spots.zip`](https://github.com/tibiamaps/tibia-map-data/files/11313136/digging-spots.zip)

You can follow our installation guide to find out which folder to place this in: https://tibiamaps.io/guides/maps-installation-windows-client

Consider donating: https://tibiamaps.io/donate
