### ISSUE TITLE
PoI - Issavi - Nykri Delta 

### ISSUE THREAD

**Issue by manuelcortes15** [tibiamaps/tibia-map-data#255]
Hi dear tibiamaps staff 
FYI

![2023-04-21_170832140_Alladyn Serior_Hotkey](https://user-images.githubusercontent.com/50208910/233747520-9fed9b32-3561-4835-ba91-3f773e6c3182.png)
![2023-04-21_171022492_Alladyn Serior_Hotkey](https://user-images.githubusercontent.com/50208910/233747531-547102d2-37d1-4820-a83b-01acb9afa5d9.png)

**Comment by manuelcortes15** [comment]
Is there another way to contribute PoI markers?¡

**Comment by manuelcortes15** [comment]
FYI: I ran `node scripts/sort-markers.mjs extra/points-of-interest/markers.json` 
[markers.json.zip](https://github.com/tibiamaps/tibia-map-data/files/11299852/markers.json.zip)


@mathiasbynens

**Comment by mathiasbynens** [comment]
Thanks! Added.
