### ISSUE TITLE
Helheim surface

### ISSUE THREAD

**Issue by Auuki** [tibiamaps/tibia-map-data#265]
Managed to snatch some photos of pois on the surface of Helheim
![2023-06-13_145352693_Hayaku Kazehaya_Hotkey](https://github.com/tibiamaps/tibia-map-data/assets/4561467/261f8aed-5d83-43d9-b5bb-246c4bab9256)
![2023-06-13_145708100_Hayaku Kazehaya_Hotkey](https://github.com/tibiamaps/tibia-map-data/assets/4561467/9bf2895e-381e-4a56-b776-e258ff8375c0)
![2023-06-13_145706276_Hayaku Kazehaya_Hotkey](https://github.com/tibiamaps/tibia-map-data/assets/4561467/94a97293-0460-4e6e-ae3d-ccfb6ca0cc17)

**Comment by muriloricci** [comment]
Marks added, plus others that I added exploring the island.
[Helheim (October 16, 2023).zip](https://github.com/tibiamaps/tibia-map-data/files/12910910/Helheim.October.16.2023.zip)

**Comment by mathiasbynens** [comment]
Thanks!
