### ISSUE TITLE
Explore wyvern cave as part of Poacher Caves

### ISSUE THREAD

**Issue by Zalameda** [tibiamaps/tibia-map-data#27]
Hello. I have been exploring free areas and expanding my map for the past few days, and today I fell in a hole east of Kazordoon. It sure is mapped on your mapper, but it is missing a (new?) wyvern cave deep inside it.

![wyvern cave](https://cloud.githubusercontent.com/assets/24754342/21467709/9b7ab3e6-c9de-11e6-9f81-a07acfe6a27f.png)

The missing cave's entrance is at X: 32779  Y: 31935   Z: 10 https://tibiamaps.io/map#32779,31935,10:2

How can I add it to the mapper?

**Comment by mathiasbynens** [comment]
Thanks for the report! Based on those coordinates, the relevant map file would be `12812410.map`.

Is this the ground floor entrance to the cave? https://tibiamaps.io/map#32756,31928,7:2 If so, I’ll explore it soon.

**Comment by Zalameda** [comment]
That's the ground floor entrance.
Its my first time contributing to mapping.
I'd like to ask if we can keep track of which sqms people tried to use pick, shovel, etc.
Let me know if there is any way I can help making the map more accurate and complete.

**Comment by mathiasbynens** [comment]
> I'd like to ask if we can keep track of which sqms people tried to use pick, shovel, etc.

There currently is no such tool available. It would be useful though!

> Let me know if there is any way I can help making the map more accurate and complete.

Please file more issues like this one, whenever you find a missing area. Thanks!
