### ISSUE TITLE
Professor Maxxen room waypoint cost

### ISSUE THREAD

**Issue by muriloricci** [tibiamaps/tibia-map-data#271]
While trying to find the best spot to stand in Professor Maxxen's room I realised the waypoint cost is missing spots.

It is currently like this:
![image](https://github.com/tibiamaps/tibia-map-data/assets/6180473/cc120891-ebc1-4eda-ad45-36f0be9eab25)

And this is what I got after walking in the room:
![image](https://github.com/tibiamaps/tibia-map-data/assets/6180473/2d4789fb-9efd-44c3-afd9-d35da4086236)

Here's the file:
[Minimap_WaypointCost_33536_32000_15.zip](https://github.com/tibiamaps/tibia-map-data/files/12896382/Minimap_WaypointCost_33536_32000_15.zip)

**Comment by mathiasbynens** [comment]
Thanks!
