### ISSUE TITLE
Map “The First Dragon” quest areas

### ISSUE THREAD

**Issue by mathiasbynens** [tibiamaps/tibia-map-data#28]
Some boss rooms have been added: https://tibia.wikia.com/wiki/First_Dragon_Quest/Spoiler

TODO: explore The First Dragon boss room

**Comment by Hunter-of-Dragoes** [comment]
There are 5 small pre-boss rooms, a big boss room and a reward room.
The pre-boss and boss rooms are located directly south from where you stopped exploring: https://tibiamaps.io/map#33590,31019,14:1
Reward room is apparently located in a different floor since I couldn't see any explored area around it on the video's minimap.

**Comment by LeeKunTibia** [comment]
I have explored all 5 pre-boss rooms, as well as the main one and reward rooms. As Hunter suspected the reward room is one floor above. 

[First Dragon Rooms.zip](https://github.com/tibiamaps/tibia-map-data/files/1666362/First.Dragon.Rooms.zip)

Also, there's an unrelated new area Hunter asked me to check, I think there's no reason to open a new issue just for it. It's under Oramond, here:

https://tibiamaps.io/map#33568,31866,13:2

For the record, this can be accessed by levitating down the room where [Dr Merlay](http://tibia.wikia.com/wiki/Dr_Merlay) is. 

Finally, a quick question: is there any reason why you did not commit the new files I sent on the _Winter Update 2017 Maps_ Issue? There are 2 ZIP files there with new explored areas. :)

**Comment by mathiasbynens** [comment]
Added. Thanks!

> Finally, a quick question: is there any reason why you did not commit the new files I sent on the Winter Update 2017 Maps Issue? There are 2 ZIP files there with new explored areas. :)

No reason, other than I haven’t gotten around to it yet. Thank you for your contributions!
