### ISSUE TITLE
Feru Ascendant - March 2024 map changes

### ISSUE THREAD

**Issue by muriloricci** [tibiamaps/tibia-map-data#288]
This includes the map changes in:

- [2024-03-12 Balancing Project Changes Part I](https://www.tibia.com/news/?subtopic=newsarchive&id=7797)
- [2024-03-19 Balancing Project Changes Part II](https://www.tibia.com/news/?subtopic=newsarchive&id=7815)

[`Feru March 2024.zip`](https://github.com/tibiamaps/tibia-map-data/files/14649121/Feru.March.2024.zip)

Differences:

![1](https://github.com/tibiamaps/tibia-map-data/assets/81942/7192f805-ffa3-4b07-9640-d3ac5807cd38)
![2](https://github.com/tibiamaps/tibia-map-data/assets/81942/7adc96f8-fe66-4986-8d8f-6f7d646850d4)
![3](https://github.com/tibiamaps/tibia-map-data/assets/81942/e6f77cec-3af1-4449-bc87-3e73fb659ac4)
![4](https://github.com/tibiamaps/tibia-map-data/assets/81942/838be122-6b28-4cd5-95a7-7ccbb04b8801)
![5](https://github.com/tibiamaps/tibia-map-data/assets/81942/8bd5fd03-d36f-46ff-8cc9-bcb2f697fc06)
![6](https://github.com/tibiamaps/tibia-map-data/assets/81942/00ccdd56-9dcb-4e13-8650-819bfd19f1ef)

**Comment by muriloricci** [comment]
Oops, forgot Pumin -2.
[Pumin Floor 2.zip](https://github.com/tibiamaps/tibia-map-data/files/14650249/Pumin.Floor.2.zip)

**Comment by mathiasbynens** [comment]
Thanks!
