### ISSUE TITLE
Re-explore lowest floor of Grounds of Despair

### ISSUE THREAD

**Issue by mathiasbynens** [tibiamaps/tibia-map-data#295]
From [the latest Balancing Changes](https://www.tibia.com/news/?subtopic=newsarchive&id=7912):

> **Grounds of Despair**
>
> On the lowest floor, we added a passage.

**Comment by muriloricci** [comment]
[Pumin.zip](https://github.com/user-attachments/files/15539275/Pumin.zip)

**Comment by mathiasbynens** [comment]
Thanks!
