### ISSUE TITLE
Dawnport-Marapur-Misc

### ISSUE THREAD

**Issue by R-o-c-k-y** [tibiamaps/tibia-map-data#296]
Dawnport Map changes, also some Marapur edging map changes amongst any other differences found within the files.
[minimap.zip](https://github.com/tibiamaps/tibia-map-data/files/15504632/minimap.zip)

**Comment by mathiasbynens** [comment]
Note to self: this is the complete `minimap` folder. We'll first need to pick only the relevant files from it, in order to avoid overwriting other parts of the map.

**Comment by mathiasbynens** [comment]
A quick and dirty way to get most of (?) the Dawnport-related files is to search for `32000_31744_`. [`dawnport-minimap.zip`](https://github.com/user-attachments/files/15521078/dawnport-minimap.zip) @R-o-c-k-y, any further filtering we can do here? Which floors are affected by your changes?

**Comment by mathiasbynens** [comment]
For Marapur: 

```
33536_32512_7
33536_32768_7
33792_32512_7
33792_32768_7
```

[`minimap-marapur.zip`](https://github.com/user-attachments/files/15521106/minimap-marapur.zip)
