### ISSUE TITLE
Exact spawn tiles of Gray Island Hive Stage 3 bane bosses

### ISSUE THREAD

**Issue by mathiasbynens** [tibiamaps/tibia-map-data#298]
Luke thinks he saw Fleshslicer appear here: https://tibiamaps.io/map#33427,31267,8:3 The tile might be off by 1 sqm still but at least it gives us a better approximation of what the exact spawn sqm might be.

Chopper: https://www.tibialight.com/post/quirefang-hive-bosses changed in 8c3a6eb25b2ff7e67958e0725d170f17a3c47098

Maw: TODO

Rotspit: TODO

Mindmasher: TODO

Shadowstalker: TODO

**Comment by mathiasbynens** [comment]
This is proof that Gray Island Hive bosses spawn with a random radius around a spawn tile, as opposed to a 100% fixed spawn tile: https://www.youtube.com/watch?v=vFbUZQJPCWw

**Comment by mathiasbynens** [comment]
> This is proof that Gray Island Hive bosses spawn with a random radius around a spawn tile, as opposed to a 100% fixed spawn tile: https://www.youtube.com/watch?v=vFbUZQJPCWw

Given this, the project to find the exact spawn tiles no longer makes sense. I’ve updated the Chopper marker description accordingly and am now closing this issue.

**Comment by muriloricci** [comment]
https://github.com/user-attachments/assets/01e16cce-1ac7-4c24-b562-39482a9d1df7

Shadowstalker (almost) captured spawning.
