### ISSUE TITLE
Thais Museum Fansite Item

### ISSUE THREAD

**Issue by R-o-c-k-y** [tibiamaps/tibia-map-data#304]
I have added all the markings for the Fansite Items locations within the minimap markers

![2024-09-16_034923226_Roc ky_Hotkey](https://github.com/user-attachments/assets/97776473-3f69-4842-a8bd-a95f5337732a)

[minimapmarkers.zip](https://github.com/user-attachments/files/17034574/minimapmarkers.zip)

**Comment by mathiasbynens** [comment]
I’ve cleaned these up and committed them for now. However, I’m not sure about the cost/benefit ratio of having these markers in the default marker pack. It seems like a niche use case, so I might move them to a separate pack to avoid everyone having to pay the performance cost of rendering the extra markers.
