### ISSUE TITLE
Unexplored pixels on ground floor

### ISSUE THREAD

**Issue by mathiasbynens** [tibiamaps/tibia-map-data#31]
https://tibiamaps.io/map#32860,32046,7:2

**Comment by BourbonCrow** [comment]
I'm like 99.9% sure those cant be reached i recall trying like a .. crazy person to get to them

**Comment by mathiasbynens** [comment]
The plan was to extract the pixel data from the official CipSoft map as shared on the fansite board. However, it looks like that map has the black pixels too 😮
