### ISSUE TITLE
Tutorial Area

### ISSUE THREAD

**Issue by Hunter-of-Dragoes** [tibiamaps/tibia-map-data#32]
The former [Flash Client tutorial](http://tibia.wikia.com/wiki/Flash_Client_Tutorial), which now can also be accessed with Tibia 11, has 3 different floors. Although you find what may seem to be ordinary stairs at the end of each floor, they actually teleport you to a very distant place, instead of one floor up/down.
I've explored it with Flash Client and exported the map to a _.exp_ file. But I think you would rather explore it by yourself on Tibia 11, am I right?
[Wounded Cave Draptor](http://tibia.wikia.com/wiki/Wounded_Cave_Draptor) and [NPC Menesto](http://tibia.wikia.com/wiki/Menesto) are located there and their location should be updated on TibiaWiki once TibiaMaps get updated.

**Comment by mathiasbynens** [comment]
[`minimap-tibia-11-tutorial.zip`](https://github.com/tibiamaps/tibia-map-data/files/868207/minimap-tibia-11-tutorial.zip)

The problem is that our scripts operate on Tibia 10-style map files.

**Comment by mathiasbynens** [comment]
Interestingly, going up the ladders goes up two floors instead of one.
