### ISSUE TITLE
Map "An Observer Eye" room

### ISSUE THREAD

**Issue by Hunter-of-Dragoes** [tibiamaps/tibia-map-data#34]
We still need to map [An Observer Eye](http://tibia.wikia.com/wiki/An_Observer_Eye) room.

It is located South of the pre-room, here: https://tibiamaps.io/map#32816,32947,14:1

**Comment by LeeKunTibia** [comment]
There you go. Just a small room right where Hunter pointed above. 
![minimap_waypointcost_32768_32768_14](https://user-images.githubusercontent.com/31053487/33795523-6c937c0c-dcca-11e7-8e48-429cc6a9df9b.png)
![minimap_color_32768_32768_14](https://user-images.githubusercontent.com/31053487/33795524-6cb19d18-dcca-11e7-961c-559cf8a57b30.png)

**Comment by mathiasbynens** [comment]
@LeeKunTibia Thanks! Could you ZIP up the original two files and attach the ZIP here instead please? GitHub compresses images upon upload :(

**Comment by LeeKunTibia** [comment]
Oh, I didn't know about that. 

[Minimap_32768_32768_14.zip](https://github.com/tibiamaps/tibia-map-data/files/1545093/Minimap_32768_32768_14.zip)
