### ISSUE TITLE
Colossus Fortress

### ISSUE THREAD

**Issue by Hunter-of-Dragoes** [tibiamaps/tibia-map-data#35]
The [Colossus Fortress](http://tibia.wikia.com/wiki/Colossus_Fortress) in Kazordoon was opened on July 11, 2013, during the test server for the first part of the Summer Update 2013 (Update 10.1).

It would be great if we could find someone who has been there and has kept the `.map` files for floors -1 and +1 to +6 (I'm not sure if floor +7 was accessible).

**Comment by mathiasbynens** [comment]
[I’ve asked around on Reddit.](https://www.reddit.com/r/TibiaMMO/comments/669box/who_managed_to_mapexplore_the_colossus_fortress/) Fingers crossed!

**Comment by Hunter-of-Dragoes** [comment]
I will ask around to tutors and senators as well.

**Comment by mathiasbynens** [comment]
After #40, this is now in the visual map data: https://tibiamaps.io/map#32591,31901,8:2 Still, it would be nice to get the original map files so we can add the pathfinding data as well.

**Comment by Sixish** [comment]
I don't think my generated map files ever had path finding data. I only
recorded the items that were in those positions on the map. The client does
not send path data, it's derived from the items in those positions.

**Comment by mathiasbynens** [comment]
Closing this since we now have the visual map data and an educated guess of the pathfinding data. Still, if someone still has those map files, we’d love to use them to improve the pathfinding data!
