### ISSUE TITLE
Zirella's roof

### ISSUE THREAD

**Issue by Hunter-of-Dragoes** [tibiamaps/tibia-map-data#36]
[Zirella](http://tibia.wikia.com/wiki/Zirella)'s house roof can be accessed if items like crates, boxes and chests are brought from Rookgaard to the Tutorial Island and stacked next to the house on the ground floor. The roof is located here: https://tibiamaps.io/map#32058,32264,6:2

**Comment by Hunter-of-Dragoes** [comment]
You can now get it from the Cyclopedia Map.

**Comment by mathiasbynens** [comment]
> You can now get it from the Cyclopedia Map.

Could you please share the image? With that I will be able to manually edit our map data.

**Comment by mathiasbynens** [comment]
Here are the files, [courtesy of Dark Gladir](https://www.reddit.com/r/Rookgaard/comments/k1t3mr/1896_screenshots_of_each_location_on_rookgaard/ge6c6aa/): [`minimap.zip`](https://github.com/tibiamaps/tibia-map-data/files/5619030/drive-download-20201130T221513Z-001.zip)
