### ISSUE TITLE
Drefia Cave

### ISSUE THREAD

**Issue by Hunter-of-Dragoes** [tibiamaps/tibia-map-data#38]
I have been to this cave and explored the 2 black rectangles here: https://tibiamaps.io/map#33037,32467,11:2
Also, one floor up, I've explored more of the rock around this part of the cave: https://tibiamaps.io/map#33069,32488,10:2
Files `12912610.map` and `12912611.map`: [Automap Drefia.zip](https://github.com/tibiamaps/tibia-map-data/files/931451/Automap.Drefia.zip)

I wonder if this part is accessible: https://tibiamaps.io/map#33011,32435,9:2

**Comment by mathiasbynens** [comment]
> I wonder if this part is accessible: https://tibiamaps.io/map#33011,32435,9:2

Good question 🤔
