### ISSUE TITLE
Summer Update 2017 new areas

### ISSUE THREAD

**Issue by molx** [tibiamaps/tibia-map-data#43]
Hello,

Lee kun here. Hunter of Dragoes told me you do not have the new maps yet, so here they are. The base for these maps is the TibiaMaps.io version of ~January this year. If you have any update after that, I don't have it. I tried getting all the corners. The new areas are:

- Feyrist, north-west of Roshamuul
- Cults areas:
    - The Misguided: entrance south of the outlaw camp, caves starting at -1 south-east of Thais, under the sea;
    - The Barkless: underneath north of Ab'Dendriel;
    - The Orcs: Edron Orcs, south-west of town;
    - The Minotaurs: teleport east of Mintwallin's entrance, caves under Sea, level -1, north of Ramoa;
    - Humans: entrace in Carlin's graveyard, dungeon under Fields of Glory;
    - Aeterna Existentia: under the Dark Pyramid north of Darashia;
    - Aurea Manus: Thais Exhibition;
    - Boss Rooms, 6 bosses + final boss, including lever rooms and anti-lever rooms. All under Edron Orcs, -8 floor. 

There are also some areas where the minimap was permanently changed:

- Talking Trees: North of Fields of Glory, west of the Amazon Tower;
- South of the Talking Trees (Not sure if minimap changed);
- Between Mount Sternum and Kazordoon's mountain, the Sentinent Stones;
- The Tooth Fairy NPC location (already on Wiki, south of the Suntower). 

I have added Sword Marks to all pre-lever, lever and boss rooms, including the text description of what boss that is. There are also many other marks related to the quests, specially on Feyrist, but those aren't documented. There are also other places with posible small minimap changes, such as 3 rooms of the Threatened Dreams quest in existing buildings of Carlin/Venore/Thais with new unmovable furniture, but these are details and I didn't pay attention to them.  

I think that's it. Let me know if you guys need anything else. 
[Minimap_Summer2017.zip](https://github.com/tibiamaps/tibia-map-data/files/1151210/Minimap_Summer2017.zip)

**Comment by mathiasbynens** [comment]
Thanks so much! I’ve been unable to play the Test Server due to not having access to my Windows computer.

Before I can merge this I’ll need to work on updating our tools to support converting `minimap` files to our own data format. This could take a while, but I’ll try to get to it as soon as possible.

**Comment by mathiasbynens** [comment]
Here’s that same data, converted to the format used in the repository.

[`data-summer2017.zip`](https://github.com/tibiamaps/tibia-map-data/files/1177934/data-summer2017.zip)

It seems the map expanded in every direction without any new content appearing in those areas. I’m assuming that is a bug in your maps? (There were also maps at coordinates `0,0`, for example, whereas the real game servers only have maps for `x` or `y` > ~30000.)

**Comment by nesleykent** [comment]
Hey, I got some maps too. I don't know if ll be useful, but my friend and I did some quest markpoints on map (moon stone, sun, tree, swan feather rewspan etc).
[minimaptestserver.zip](https://github.com/tibiamaps/tibia-map-data/files/1178726/minimaptestserver.zip)

**Comment by molx** [comment]
I did not expect to have any weird things on my maps like that. I definitely did not edit them manually and they are relatively new, from TibiaMaps. Unfortunately I did not find any secret area that should be there, hahaha. I'm glad you found a way to use the new format. :)

**Comment by Hunter-of-Dragoes** [comment]
I'll list here some missing places:
- [ ] All daily reward shrines: <every city's temple and depot>
- [ ] Fire Shrine in Kha'zeel Dragon Lairs/Tiquanda
- [ ] Ice Shrine underneath the Chakoya Iceberg 
- [ ] Area near this Banshee Quest lever: https://tibiamaps.io/map#32267,31860,11:2

**Comment by mathiasbynens** [comment]
Is it true that Port Hope’s depot doesn’t have a reward shine?

**Comment by mathiasbynens** [comment]
Port Hope’s depot doesn’t seem to have a reward shine. Is this correct, or am I missing something?

**Comment by LeeKunTibia** [comment]
The Warzone bosses' rooms are still missing (the original files above have these maps). They should be here:

https://tibiamaps.io/map#33142,31927,7:0

**Comment by Hunter-of-Dragoes** [comment]
Old areas that were changed such as cave expansions should be rechecked. I found this a while ago, it is the way to a cult cave (no wall there anymore): https://tibiamaps.io/map#33298,32291,11:4

It seems like new explored areas were added to the already explored map, so map changes like walls becoming walkable tiles were not caught.

And there is a gap in the Prize Exhibition here which should be explored: https://tibiamaps.io/map#32518,32176,10:1

**Comment by Hunter-of-Dragoes** [comment]
Area around [NPC Tired Tree](http://tibia.wikia.com/wiki/Tired_Tree).
[Map.zip](https://github.com/tibiamaps/tibia-map-data/files/1563512/Map.zip)

**Comment by mathiasbynens** [comment]
@LeeKunTibia 

> The Cults of Tibia bosses' rooms are still missing (the original files above have these maps). They should be here: https://tibiamaps.io/map#33142,31927,7:0

Are you sure that’s the correct link? I compared the `33024_31744_7` files and didn’t see a difference. I also checked other `33024_31744_*` floors and didn’t see anything there. Can you please clarify?

**Comment by LeeKunTibia** [comment]
> Are you sure that’s the correct link? I compared the 33024_31744_7 files and didn’t see a difference. I also checked other 33024_31744_* floors and didn’t see anything there. Can you please clarify?

I'm sorry, it's all there, I'm not sure why I couldn't find it... They are here:

https://tibiamaps.io/map#33119,31913,15:1

**Comment by Hunter-of-Dragoes** [comment]
Thais Prize Exhibition last floor explored.

[Map Museum (new).zip](https://github.com/tibiamaps/tibia-map-data/files/1584995/Map.Museum.new.zip)

**Comment by LeeKunTibia** [comment]
There is a small glitch around this area:

https://tibiamaps.io/map#32722,31584,8:3

I don't know why, but there are some wall tiles where it's regular walking floor. I just went there and couldn't map click until I walked close to it and the map updated. Sending the corrected maps. It's the Barkless Cult area, just FYI. 
[Barkless Area.zip](https://github.com/tibiamaps/tibia-map-data/files/1641400/Barkless.Area.zip)

**Comment by Hunter-of-Dragoes** [comment]
Area around [NPC Tooth Fairy](http://tibia.wikia.com/wiki/Tooth_Fairy).

[Minimap_Color_32512_31488_7.zip](https://github.com/tibiamaps/tibia-map-data/files/1713384/Minimap_Color_32512_31488_7.zip)

**Comment by Hunter-of-Dragoes** [comment]
[These wall fields](https://tibiamaps.io/map#32487,32101,15:3) in Mintwallin entrance were removed.

[Minimap_Color_32256_32000_15.zip](https://github.com/tibiamaps/tibia-map-data/files/1713391/Minimap_Color_32256_32000_15.zip)

**Comment by Hunter-of-Dragoes** [comment]
[This wall field](https://tibiamaps.io/map#33298,32291,11:3) in the Dark Pyramid was also removed.

[Minimap_Color_33280_32256_11.zip](https://github.com/tibiamaps/tibia-map-data/files/1713460/Minimap_Color_33280_32256_11.zip)

**Comment by mathiasbynens** [comment]
@LeeKunTibia Re: https://github.com/tibiamaps/tibia-map-data/issues/43#issuecomment-358518750 There seems to be no difference between the files you’ve uploaded and the data that’s already in the repo. 🤔 Did I do something wrong?

@Hunter-of-Dragoes Thanks! I’ve addressed your last three comments.

**Comment by Hunter-of-Dragoes** [comment]
> There seems to be no difference between the files you’ve uploaded and the data that’s already in the repo. Did I do something wrong?

The issue he mentioned was already fixed. There is nothing to worry now.

**Comment by mathiasbynens** [comment]
Closing this for now.

**Comment by Hunter-of-Dragoes** [comment]
> * [ ]  Area near this Banshee Quest lever: https://tibiamaps.io/map#32267,31860,11:2

Better late than never. 😉
[Banshee Quest Lever Map.zip](https://github.com/tibiamaps/tibia-map-data/files/5546875/Banshee.Quest.Lever.Map.zip)

**Comment by mathiasbynens** [comment]
Oh yay! Thanks for the maps. I guess I'll reopen the issue too, since there are still some unresolved items in https://github.com/tibiamaps/tibia-map-data/issues/43#issuecomment-324515684.
