### ISSUE TITLE
Map area below nomad’s bridge

### ISSUE THREAD

**Issue by mathiasbynens** [tibiamaps/tibia-map-data#46]
<https://secure.tibia.com/forum/?action=thread&threadid=4536276>

> So exploring around chor today looking for the dragon and dragon lord you see now as you run to tiquanda, I found a new dragon spawn and a small spawn of 3 wyvrns. If you teleport above them you're capable of reaching the nomad's bridge. I thought this was pretty cool because I've never seen anyone over here and my downloaded maps didn't have the place mapped.
> 
> I thought I'd share in case this could somehow relates to a quest, or for noobs to run over and grab some items people thought no one could get. 
>
> ![](https://user-images.githubusercontent.com/81942/33234434-0e6afc66-d227-11e7-9490-28ada6089bee.png)

**Comment by LeeKunTibia** [comment]
This issue also seems to be solved. I just visited the area and it's right [here](https://tibiamaps.io/map#33022,32798,3:2). It's actually a little bit over-explored since that patch of sand to the east does not exist.
