### ISSUE TITLE
Finish mapping Ferumbras' Ascension Quest area

### ISSUE THREAD

**Issue by LeeKunTibia** [tibiamaps/tibia-map-data#47]
There's at least one seal of the Quest Area that is not fully explored:

https://tibiamaps.io/map#33403,32350,13:1

**Comment by mathiasbynens** [comment]
The relevant ID is `33280_32256_13`, meaning the files are:

```
minimap/Minimap_Color_33280_32256_13.png
minimap/Minimap_WaypointCost_33280_32256_13.png
```

If anyone reading this has this cave fully explored, please upload a ZIP file with these two files in it. Thank you!

**Comment by mathiasbynens** [comment]
I’ve asked r/TibiaMMO for help: https://www.reddit.com/r/TibiaMMO/comments/8nqcxf/need_help_mapping_ferumbras_ascension_quest_area/
