### ISSUE TITLE
Ankrahmun MWC Areas

### ISSUE THREAD

**Issue by Hunter-of-Dragoes** [tibiamaps/tibia-map-data#50]
[Nomads MWC](http://tibia.wikia.com/wiki/Nomads_Mini_World_Change/Spoiler) area south of the Ancient Ruins Tomb, [here](https://tibiamaps.io/map#33201,32616,7:1).

[Nightmare Isles MWC](http://tibia.wikia.com/wiki/Nightmare_Isles_Mini_World_Change/Spoiler) area northeast of Tarpit Tomb, [here](https://tibiamaps.io/map#33259,32653,7:1).

At the same time, it would be nice to **not** change the entrance to the [Otherworld](http://tibia.wikia.com/wiki/Otherworld), [here](https://tibiamaps.io/map#33167,32639,7:1).

[Minimap_Color_33024_32512_7.zip](https://github.com/tibiamaps/tibia-map-data/files/1713414/Minimap_Color_33024_32512_7.zip)

**Comment by benjaminkomen** [comment]
Are you sure you want those areas added to the map, while they may, or may not be there (depending on the MWC taking place or not)?

**Comment by mathiasbynens** [comment]
Until now we’ve added MWC areas only in cases where the MWC is purely additive. It seems like these two don’t add new areas but exclusively overwrite others. 🤔 Not sure what the best way forward is. Would including all MWC areas be useful for TibiaWiki?

**Comment by Hunter-of-Dragoes** [comment]
When I saw [this Nomads MWC area](https://tibiamaps.io/map#33237,32569,7:1), I assumed you wanted to map them all.

> Would including all MWC areas be useful for TibiaWiki?

Yes, including them would be useful to TibiaWiki when pointing their location on our mapper. Does it take much of your time to include those areas?

**Comment by mathiasbynens** [comment]
> Yes, including them would be useful to TibiaWiki when pointing their location on our mapper. Does it take much of your time to include those areas?

Okay, if it’s useful for TibiaWiki then I’ll change our policy, and add these MWC areas to the map data.
