### ISSUE TITLE
Island West of Meluna

### ISSUE THREAD

**Issue by Hunter-of-Dragoes** [tibiamaps/tibia-map-data#53]
Screenshot taken from Cyclopedia's Map.

[Island West of Meluna.zip](https://github.com/tibiamaps/tibia-map-data/files/2073372/Island.West.of.Meluna.zip)

**Comment by mathiasbynens** [comment]
I think you managed to get the minimap files for this area now, didn’t you?

**Comment by mathiasbynens** [comment]
Ref. #56.

[`new-island.tar.gz`](https://github.com/tibiamaps/tibia-map-data/files/2086919/new-island.tar.gz)
