### ISSUE TITLE
Map The Ancient Spawn of Morgathla Reward Rooms

### ISSUE THREAD

**Issue by LeeKunTibia** [tibiamaps/tibia-map-data#58]
There are three rewards rooms related to The Ancient Spawn of Morgathla, but we currently only have one them mapped. The second can can be seen [here](https://tibiamaps.io/map#33769,32315,15:2) and the third is most likely just near these two. It would also be a good time to get the maps around the boss fight rooms so they look better.

**Comment by LeeKunTibia** [comment]
I got the files for the west reward room.

[Minimap_33536_32256_15.zip](https://github.com/tibiamaps/tibia-map-data/files/3044946/Minimap_33536_32256_15.zip)

I merged them manually, so in case something goes wrong that's probably the reason. If it happens I'll send you the original files I received.

**Comment by mathiasbynens** [comment]
Re-opening as we still need the other room.

**Comment by LeeKunTibia** [comment]
More than three years later, finally got these maps from a friend! 

[Morgathla Rewards.zip](https://github.com/tibiamaps/tibia-map-data/files/6914026/Morgathla.Rewards.zip)

We can close this after this update.

**Comment by mathiasbynens** [comment]
Awesome! Happy to finally close this one 🥳
