### ISSUE TITLE
Feature Request: display map file coordinates on website Map Viewer

### ISSUE THREAD

**Issue by LeeKunTibia** [tibiamaps/tibia-map-data#59]
I think it would be very helpful if the website map viewer showed the corresponding map file coordinates of the selected location. It would make searching for the required files to update an area much easier. 

Edit: I just realized I should have opened this on /tibia-map since it's a website feature, sorry about that. Feel free to close it and I'll open it there.

**Comment by mathiasbynens** [comment]
Would you mind copy-pasting this issue here? https://github.com/tibiamaps/tibia-map/issues Thanks!
