### ISSUE TITLE
Fix Waypoint Maps

### ISSUE THREAD

**Issue by LeeKunTibia** [tibiamaps/tibia-map-data#61]
For some reason, some areas have their waypoint data completely "blocked", i.e. it's painted as non-walkable (yellow) and thus you get a lot of "There is no way." when using the maps. For example, [Calassa](https://tibiamaps.io/map#32019,32754,12:0). Here is my Waypoint files before (left) and after (right) "manually" walking around it:

![image](https://user-images.githubusercontent.com/31053487/42716560-7d503550-86d2-11e8-92fe-41d1281712fa.png)

The following files are involved here: `32000_32512_12`, `32000_32768_12`, `31744_32512_12` and `31744_32768_12`.

I have had reports about other areas as well (the Emperor's Castle), but I don't know if in this case it's the same problem or just one-sqm passages being blocked (I think old versions saved creatures position in the map and led to this, right? It has happened to me in narrow places such as the path to Hellgate).

**Comment by mathiasbynens** [comment]
Could you share the updated files please? Thanks.

**Comment by LeeKunTibia** [comment]
I didn't really open it all, which is why I didn't send them yet. If you don't mind I rather leave this issue here for now as a reminders for me (but also for others) and I'll try to remap it when I have the time.

**Comment by mathiasbynens** [comment]
Sounds good to me. Thank you so much for filing the issue!

**Comment by LeeKunTibia** [comment]
I went there to discover and also mapped again. But to make sure I didn't miss any spot I removed the files, so the rest of the areas of the same files are empty. You can merge them, right? 

[Calassa Waypoints.zip](https://github.com/tibiamaps/tibia-map-data/files/2215912/Calassa.Waypoints.zip)
