### ISSUE TITLE
Re-map new Asura Palace

### ISSUE THREAD

**Issue by mathiasbynens** [tibiamaps/tibia-map-data#63]
Quoting @LeeKunTibia ([source](https://github.com/tibiamaps/tibia-map-data/issues/56#issuecomment-404380278)):

> I have bad news: CipSoft has widened some corridors of the new Asura Palace between the TS and now. The current maps aren't correct. Unfortunately I did not remap everything and my map is also buggy:
> 
> ![](https://user-images.githubusercontent.com/31053487/42611370-2aac8f04-856c-11e8-83dc-8f281270973e.png)
> 
> We need to map this area again.

**Comment by LeeKunTibia** [comment]
I ended up going there again and remapping the problematic areas, as far as I can tell it's 100% now. By the way, this also fixes the already existing bug [here](https://tibiamaps.io/map#32865,32774,9:2). 

[Asura Palace Fix.zip](https://github.com/tibiamaps/tibia-map-data/files/2215604/Asura.Palace.Fix.zip)
