### ISSUE TITLE
New Dark Stone Totem Location

### ISSUE THREAD

**Issue by Hunter-of-Dragoes** [tibiamaps/tibia-map-data#64]
A [Dark Stone Totem](https://tibia.wikia.com/wiki/Dark_Stone_Totem) was added [here](https://tibiamaps.io/map#32277,31736,7:3) with the Summer Update. It's a black, non-walkable pixel. Since it is just 1 pixel, I won't upload the _32256_31488_7_ map files.

**Comment by mathiasbynens** [comment]
> Since it is just 1 pixel, I won't upload the 32256_31488_7 map files.

Actually, uploading the updated minimap PNGs is the easiest way to get the data merged. Just FYI!

**Comment by alfredomtx** [comment]
Here it is the minimap file with the totem:
[Minimap_Color_32256_31488_7.zip](https://github.com/tibiamaps/tibia-map-data/files/5939461/Minimap_Color_32256_31488_7.zip)
