### ISSUE TITLE
Re-explore Sunken Temple entrance

### ISSUE THREAD

**Issue by mathiasbynens** [tibiamaps/tibia-map-data#67]
We have maps for this area but it looks like they’re not correct, or the area has been updated since we’ve explored it.

https://tibia.wikia.com/wiki/Sunken_Temple
https://tibiamaps.io/map#32870,32520,8:2

**Comment by LeeKunTibia** [comment]
Why do you think it is incorrect? The link you posted is south of the temple. The temple is north of it, and I can't see any problem with the maps:

https://tibiamaps.io/map#32881,32468,9:2

**Comment by mathiasbynens** [comment]
Someone just reported the same issue through our Facebook page:

> Hey guys, you need to add the entrance in Port Hope  where can win achievement SPECTULATION

That's the same place where I noticed the issue.

**Comment by LeeKunTibia** [comment]
Oh, I got it now - the ground-floor entrance is missing. I thought you were referring to the underground area. 

The north-most pixel of the building is part of another file, so there are 2 separate files for the fix.

[Deathling Temple fix.zip](https://github.com/tibiamaps/tibia-map-data/files/2677919/Deathling.Temple.fix.zip)
