### ISSUE TITLE
Area below nomad’s bridge

### ISSUE THREAD

**Issue by mathiasbynens** [tibiamaps/tibia-map-data#69]
I’m not sure if we have this area mapped already: https://www.tibia.com/forum/?action=thread&threadid=4536276

![](https://user-images.githubusercontent.com/81942/44663766-cc9a3d80-a9e7-11e8-9a16-2f47240b060b.png)

**Comment by Hunter-of-Dragoes** [comment]
Yes, that area is already mapped, check https://tibiamaps.io/map#33022,32773,3:2.

**Comment by mathiasbynens** [comment]
Nice!
