### ISSUE TITLE
Grounds of Deceit - Ferumbras' Ascension Quest

### ISSUE THREAD

**Issue by LeeKunTibia** [tibiamaps/tibia-map-data#70]
Yet another part of the quest area is missing. This is the seal of Zamulosh:

https://tibiamaps.io/map#33646,32647,10:1

I asked the used who sent the Ferumbras maps last time a few weeks ago but he doesn't have these.

**Comment by LeeKunTibia** [comment]
Here they are! 

[Zamulosh.zip](https://github.com/tibiamaps/tibia-map-data/files/2540859/Zamulosh.zip)

**Comment by LeeKunTibia** [comment]
> Here they are!
> 
> [Zamulosh.zip](https://github.com/tibiamaps/tibia-map-data/files/2540859/Zamulosh.zip)

Actually, the Path file here is empty, so better not replace it.

**Comment by mathiasbynens** [comment]
Thanks!
