### ISSUE TITLE
Fix Dragonblaze Peaks Tracked Map

### ISSUE THREAD

**Issue by LeeKunTibia** [tibiamaps/tibia-map-data#75]
There is an area of the Dragonblaze Peaks that is incorrectly mapped due to tracking:

https://tibiamaps.io/map#33187,31296,5:1

Floors above and below are also problematic, but they cannot be explored as usual. I suggest using the Cyclopedia map for that, it should be possible to cut it perfectly to replace the Color files, but not the Waypoint files.

[Minimap_Color_33024_31232_5.zip](https://github.com/tibiamaps/tibia-map-data/files/2677936/Minimap_Color_33024_31232_5.zip)

**Comment by mathiasbynens** [comment]
I’ve patched in the files you sent.

Could you please share the Cyclopedia map files for these floors so I can start cropping? (You could email them privately if you prefer.)

**Comment by LeeKunTibia** [comment]
Here they are.

I'll try to add a button to generate the cropped files for us already so in the future I can send those already (though I'm not sure if that limited color palette thing will be a problem). Do you think we should give them priority over explored maps? Specially the ground floor, there are places in which we don't have the full borders (for example some small mountain parts around the Falcon Bastion). 

[Minimap Cyclopedia 2-7.zip](https://github.com/tibiamaps/tibia-map-data/files/2683780/Minimap.Cyclopedia.2-7.zip)

**Comment by mathiasbynens** [comment]
@LeeKunTibia Thank you!

FYI, don't worry about the limited color palette thing in this case. If you send me the PNG files I can use our tools to convert them back to the custom format we use in this repository. That's what I do for every suggestion that comes in here where someone contributes minimap files.

Our minimap -> custom `*.png` + `markers.json` tooling doesn't care about the limited color palette. We only worry about that when we *generate* `minimap` files.

**Comment by LeeKunTibia** [comment]
Closing this, should be fixed and Odyssey bugs can be tracked in #65.
