### ISSUE TITLE
Winterlight Solstice

### ISSUE THREAD

**Issue by LeeKunTibia** [tibiamaps/tibia-map-data#77]
The Percht Island is located north-east of Quirefang. Two sets of coordinates, two floors up and two floors down. 

On the ground floor a small part of the mountain is not explorable - it's currently blue because it was previously sea. If possible please paint it gray like the mountain. 

The area in Svargrond's harbor where the new boat is also changed, but we don't know if the change will be permanent of gone once the event is over. 

[Winterlight Solstice.zip](https://github.com/tibiamaps/tibia-map-data/files/2706192/Winterlight.Solstice.zip)

**Comment by mathiasbynens** [comment]
> On the ground floor a small part of the mountain is not explorable - it's currently blue because it was previously sea. If possible please paint it gray like the mountain.

Thanks for pointing that out! I’ve manually fixed up the maps and merged them with our data.

**Comment by benjaminkomen** [comment]
Thanks for the quick release!

**Comment by mathiasbynens** [comment]
I’ve added some markers (using [our marker spreadsheet](https://docs.google.com/spreadsheets/d/1K6hEPmxUCFj293yCkMAphX2UvJRgTaLqt465J48hJO4/edit)) in eb9582b1c6ba2bfc0dc6f3ee070aa513f5cd1da8.
