### ISSUE TITLE
Map the Isle of Solitude

### ISSUE THREAD

**Issue by mathiasbynens** [tibiamaps/tibia-map-data#8]
I don’t even know what this is, but the Tibia Wikia mapper has it: http://tibia.wikia.com/wiki/Mapper?coords=126.63-124.190-7-1-1-1

![](https://cloud.githubusercontent.com/assets/81942/11907529/ed22ab74-a5d4-11e5-9ce8-0e642a8ceacd.png)

**Comment by Sixish** [comment]
This is the Isle of Solitude. It was mapped by a former GM, I believe. It's not accessible by normal means.

**Comment by mathiasbynens** [comment]
In that case, we have two options:

* leave it unexplored, since it’s not really accessible during regular gameplay
* fake it: copy the pixel data (which would take care of `floor-07-map.png`), and make an educated guess as to what the pathing data would be (`floor-07-path.png`)

I don’t have a strong preference here, but for TibiaWiki purposes it might be best to have it mapped somehow.

**Comment by mathiasbynens** [comment]
Option three: * get the `12612407.map` file somehow (from the former GM, perhaps — assuming they still have it)
