### ISSUE TITLE
Fix Souleater Mountains tracked map

### ISSUE THREAD

**Issue by LeeKunTibia** [tibiamaps/tibia-map-data#80]
Similar to other locations, the Souleater Mountains have some artificial areas which were replicated during map tracking. For example, this area here doesn't exist and is a copy from the identical small area to the west:

https://tibiamaps.io/map#33190,31077,4:2

Also, this small area has been replicated both to the south and east:

https://tibiamaps.io/map#33176,31020,4:2

(These problems are also present on the floors directly above and below floor 4).

I have re-explored the area but it's not possible to reach and clean some of it. I have the Cyclopedia files, but I think that instead of sending them now as one big file I'll edit my tool to create separate minimap files with the exact coords and we can use this for pretty much all the map with the exception of areas not on the Cyclopedia (e.g. Dream Courts). Once I have that I'll upload them here and on other similar issues.

**Comment by LeeKunTibia** [comment]
Better late than never... Here are the Cyclopedia map files of these mountains to remove duplicated maps from tracked data.

[Souleater Mountains.zip](https://github.com/tibiamaps/tibia-map-data/files/5604484/Souleater.Mountains.zip)

**Comment by mathiasbynens** [comment]
@LeeKunTibia Thanks! I've merged that in. Closing the issue for now, but let me know if there's more to do here.
