### ISSUE TITLE
Orcsoberfest

### ISSUE THREAD

**Issue by mathiasbynens** [tibiamaps/tibia-map-data#83]
Orcsoberfest island is a big problem, since it’s in the exact same map location as the Winterlight Solstice island. That is, our map data cannot simultaneously contain both areas in their fully mapped form.

I propose adding only the (parts of the) areas that do not overlap to the map data.

Some random points of interest:

- The main island: https://tibiamaps.io/map#33771,31062,7:1
- Schnitzel boss room: https://tibiamaps.io/map#33713,31116,9:1

**Comment by mathiasbynens** [comment]
[ZIP file with Frankenstein’d map files](https://github.com/tibiamaps/tibia-map-data/files/3739804/fixed.zip)

**Comment by igordelecrode** [comment]
Would you have img without overlapping? I know because of the problem you inserted one on top of the other, but before we had the perfect ice island, would you have the perfect orc island without overlapping?

I tried to catch but the event is already over ....

**Comment by igordelecrode** [comment]
![orcfaltando](https://user-images.githubusercontent.com/21036806/67138207-53c2fa00-f216-11e9-8a3c-f39b8949fa93.png)

what I got has some pieces missing ...

**Comment by mathiasbynens** [comment]
> Would you have img without overlapping? I know because of the problem you inserted one on top of the other, but before we had the perfect ice island, would you have the perfect orc island without overlapping?

I didn’t explore Orcsoberfest island with a clean/empty map, so the files I have do have some parts of the Winterlight Solstice island. You could manually remove those parts to get the Orcsoberfest-only map you seek. I’ve attached the minimaps with the Orcsoberfest on top here: 
[`minimap-with-orcsoberfest-visible.zip`](https://github.com/tibiamaps/tibia-map-data/files/3829242/minimap-with-orcsoberfest-visible.zip)

**Comment by mathiasbynens** [comment]
Hunter sent me his extended map files: [`Orcsoberfest_Maps.zip`](https://github.com/tibiamaps/tibia-map-data/files/3847177/Orcsoberfest_Maps.zip) It contains some areas that are missing our current maps.

**Comment by Hunter-of-Dragoes** [comment]
What happened to [these caves](https://tibiamaps.io/map#33809,31087,9:1)?

**Comment by LeeKunTibia** [comment]
> What happened to [these caves](https://tibiamaps.io/map#33809,31087,9:1)?

Looks like they got list in the merging of areas, but the Orcsoberfest part of this file ([33792_30976_9]) can be found on the  `minimap-with-orcsoberfest-visible-and-winter-removed.zip` file Mathias uploaded above.

**Comment by mathiasbynens** [comment]
I'm fixing this based on the floor 09 images from 47a0cfc027c6f299e034f2ff9bfe87bf30487763.

**Comment by mathiasbynens** [comment]
Closing this in favor of #104. We can now have separate map files for Orcsoberfest Island and for Percht Island.
