### ISSUE TITLE
House update 2019

### ISSUE THREAD

**Issue by mathiasbynens** [tibiamaps/tibia-map-data#85]
We need to explore [the new houses](https://www.tibia.com/news/?subtopic=newsarchive&id=5267).

Note that CipSoft [stated](https://www.tibia.com/forum/?action=thread&postid=38806910#post38806910) that this “house update” is independent from the Winter Update (#84) and will likely happen sooner.

**Comment by LeeKunTibia** [comment]
List of new houses:

Ab'Dendriel - Treetop - Prima Arbor

Carlin - Theater Avenue - Tower

Carlin - Wilderness around Carlin - Caretaker's Residence

Darashia - Darashia, Border - Pirate Shipwreck 1

Darashia - Darashia, Border - Pirate Shipwreck 2

Edron - Castle of Edron - Castle, Residence

Edron - Wood Avenue - Stronghold

Kazordoon - The Farms - Dwarven Magnate's Estate

Kazordoon - The Market - Forge Master's Quarters

Liberty Bay - Liberty Bay, upper class - Ivory Mansion

Port Hope - Port Hope, Marketplace - Haggler's Hangout 7

Port Hope - Port Hope, Marketplace - Big Game Hunter's Lodge

Svargrond - Svargrond, upper class - Lakeside Mansion

Thais - Harbour Place - Harbour Place 3

Thais - The City Wall - Smuggler's Den

Venore - Mystic Lane - Mystic Lane 3 (Tower)

Venore - Lucky Lane - Lucky Lane 2 (Tower)

Venore - Lucky Lane - Lucky Lane 3 (Tower)

Venore - Iron Alley - Iron Alley Watch, Upper

Venore - Iron Alley - Iron Alley Watch, Lower

Yalahar - Yalahar, Centre - Harbour Promenade 1

Yalahar - Yalahar, Centre - Luminous Arc 5

Yalahar - Yalahar, Centre - Aureate Court 5

Yalahar - Yalahar, Centre - Mad Scientist's Lab

**Comment by mathiasbynens** [comment]
List of changes: https://github.com/mathiasbynens/tibia.com-extension/commit/45c96eeb23f0f83008845661fc1b169ecfbbc536

Up-to-date machine-readable list of buildings in Tibia: https://github.com/mathiasbynens/tibia.com-extension/blob/master/data/buildings.js

**Comment by mathiasbynens** [comment]
I’m not sure, but I _think_ the Kazordoon elevator was introduced as part of the house update. I’ve explored it here: acf910703edf152e0f79b59f3c9cf76f3df193b9

**Comment by LeeKunTibia** [comment]
Interesting find! 

If you jump down - instead of using the lever - you can actually explore the elevator floor by floor, so there are more maps to change:

[Kazz Elevator 3-7.zip](https://github.com/tibiamaps/tibia-map-data/files/4045946/Kazz.Elevator.3-7.zip)

**Comment by mathiasbynens** [comment]
Right, I had actually explored those but had forgotten to add them to the data 🤦‍♂ Thanks, @LeeKunTibia!

**Comment by mathiasbynens** [comment]
https://tibia.fandom.com/wiki/Updates/12.20.9260

The "new" houses are now all open for visits on the Test Server!

**Comment by Hunter-of-Dragoes** [comment]
I've just mapped all houses that were added or changed with Update 12.20.9260. Here are my files.

Since I used the map package with no markers (_minimap-without-markers.zip_), I think you should disregard my _minimapmarkers.bin_ file.

Unfortunately, when travelling to Carlin and Ankrahmun, I ended up erasing part of Yasir's ship on those cities. So, if you can, try to keep it. :)

[minimap-without-markers.zip](https://github.com/tibiamaps/tibia-map-data/files/5534204/minimap-without-markers.zip)

**Comment by mathiasbynens** [comment]
> (still need to remove the files that include Yasir areas)

Ended up manually editing out just the Yasir areas, to ensure we merge all the other changes from these files.
