### ISSUE TITLE
Isle of Merriment

### ISSUE THREAD

**Issue by mathiasbynens** [tibiamaps/tibia-map-data#86]
https://www.tibia.com/news/?subtopic=newsarchive&id=5283

- [`minimap.zip`](https://github.com/tibiamaps/tibia-map-data/files/3859777/minimap.zip) (mine)
- [`Merriment_Island.zip`](https://github.com/tibiamaps/tibia-map-data/files/3859795/Merriment_Island.zip) (thanks to gred)

**Comment by LeeKunTibia** [comment]
I was arrested by Mirade today on the island and with that explored a little bit more of the underground:

[Minimap_WaypointCost_31744_31744_8.zip](https://github.com/tibiamaps/tibia-map-data/files/10061416/Minimap_WaypointCost_31744_31744_8.zip)

![image](https://user-images.githubusercontent.com/31053487/203182339-d3c6c3bc-7974-4b17-a4a6-1ef0ac663dd4.png)

**Comment by mathiasbynens** [comment]
Hilarious! Added :)
