### ISSUE TITLE
Some Rope Tiles marked as non-walkable

### ISSUE THREAD

**Issue by thiagoretes** [tibiamaps/tibia-map-data#91]
Some rope spots are walkable and marked as non-walkable on pathfinding, such as: X: 940 Y:1663 Z: 10

Any possible solution aside of marking manually them?

**Comment by mathiasbynens** [comment]
There's a few options:

- manually mark them
- upload a ZIP of the modified `minimap` files after re-exploring the area

**Comment by thiagoretes** [comment]
Will, look forward it, thanks!

**Comment by mathiasbynens** [comment]
Closing this for now. Please upload the ZIP and re-open the issue once you've had a chance! Thanks.
