### ISSUE TITLE
The Cube map

### ISSUE THREAD

**Issue by LeeKunTibia** [tibiamaps/tibia-map-data#97]
Back in April CipSoft added a new part of the Opticording Spheres Quest. I just noticed this was never added to TibiaMaps. The new areas are:

- The _site_ under Gray Beach, [here](https://tibiamaps.io/map#33552,31419,15:1)
- The Cube area itself, around [here](https://tibiamaps.io/map#33842,32495,14:0)
- The floor below The Cube, that wasn't supposed to be reachable but was due to levitate bugs. 

Due to me not sending these before and replacing the files with SU files, I lost part of the maps. So far I wasn't able to recover the western files of the bugged floor, I'm asking some friends if they have it, if they don't we'll have to ask for those in Reddit as not many players explored that area. The coord files we're missing are:

```
33536_32256_15
33536_32512_15
```

The rest of the files with most of the rooms: [The Cube.zip](https://github.com/tibiamaps/tibia-map-data/files/4948706/The.Cube.zip)

For the record, this is how the now unreachable map looks like: 
![image](https://user-images.githubusercontent.com/31053487/87957999-5c877b80-ca87-11ea-8b55-d732d9a27cfd.png)

**Comment by LeeKunTibia** [comment]
I was able to get the west map files from a friend. They weren't complete but since the area is a big square I used that to complete the gaps. Also re-sending part of the cube with a bit more exploration.

[Second batch.zip](https://github.com/tibiamaps/tibia-map-data/files/4954952/Second.batch.zip)

**Comment by mathiasbynens** [comment]
Awesome!
