### ISSUE TITLE
Bog God Temple, 3rd level

### ISSUE THREAD

**Issue by Maddogs1964** [tibiamaps/tibia-map-data#98]
`Minimap_Color_33024_32000_5.png`

![Minimap_Color_33024_32000_5](https://user-images.githubusercontent.com/52962104/88324781-15fe7f00-cd1c-11ea-8d66-2179bb383348.png)

**Comment by mathiasbynens** [comment]
Thanks! Do you have the corresponding `Minimap_WaypointCost_33024_32000_5.png` file too?

**Comment by Maddogs1964** [comment]
As requested

**Comment by mathiasbynens** [comment]
I don't see an image in your post, unfortunately. I think GitHub does not support file attachments in emails :( You might need to upload the file on the web interface, on the issue you filed, here: https://github.com/tibiamaps/tibia-map-data/issues/98 Thanks!

**Comment by mathiasbynens** [comment]
Uploading the image straight to GitHub apparently messed with it in a way that makes this hard to merge accurately. We'll need to remap this and upload the images in a ZIP instead.

**Comment by mathiasbynens** [comment]
I think this might be resolved by #190.
